### ISSUE TITLE
tns livesync ios error on before-watch hook

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-cli#1676]
Hi I'm following the [Building Apps with NativeScript and Angular 2](https://tjvantoll.github.io/nativescript-angular-guide/) to build the groceries app. It works fine when I run `tns run ios --emulator` or `tns livesync ios --emulator`, but if I want to watch my files, doesn't work at al..
Is that any way to reload without watch?

I'm trying to run the follow command:
`tns livesync ios --emulator --watch`

Here's the error that happens on `before-watch hook` which is basically a require to the file 
`nativescript-dev-typescript/lib/watch.js`

I've runned a trace and the log is on [pastebin](http://pastebin.com/d2iVSWmT).
I post here the main errors:

### Errors
```shell
BeforeHookName for command watch is before-watch
Executing before-watch hook from /Users/lcaseiro/Sites/native-script-groceries/hooks/before-watch/nativescript-dev-typescript.js
Executing before-watch hook at location /Users/lcaseiro/Sites/native-script-groceries/hooks/before-watch/nativescript-dev-typescript.js in-process
Found peer TypeScript 1.8.10
Hook promises to signal completion
fs.js:1315
    throw error;
    ^

Error: watch /users/lcaseiro/sites/native-script-groceries ENOENT
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at addDirWatcher (/Users/lcaseiro/Sites/native-script-groceries/node_modules/typescript/lib/tsc.js:1036:39)
    at Object.addFile (/Users/lcaseiro/Sites/native-script-groceries/node_modules/typescript/lib/tsc.js:1051:21)
    at Object.watchFile (/Users/lcaseiro/Sites/native-script-groceries/node_modules/typescript/lib/tsc.js:1172:48)
    at Object.executeCommandLine (/Users/lcaseiro/Sites/native-script-groceries/node_modules/typescript/lib/tsc.js:34546:44)
    at Object.<anonymous> (/Users/lcaseiro/Sites/native-script-groceries/node_modules/typescript/lib/tsc.js:34877:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

Failed during hook execution.
TypeScript compiler failed with exit code 1
```

### npm packages:
```
├── angular2@2.0.0-beta.9
├── es6-promise@3.1.2 extraneous
├── es6-shim@0.33.13 extraneous
├─┬ nativescript-angular@0.0.38
│ └── es6-shim@0.33.13
├─┬ nativescript-dev-typescript@0.3.1
│ └─┬ nativescript-hook@0.2.1
│   ├─┬ glob@6.0.4
│   │ ├─┬ inflight@1.0.4
│   │ │ └── wrappy@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├─┬ minimatch@3.0.0
│   │ │ └─┬ brace-expansion@1.1.3
│   │ │   ├── balanced-match@0.3.0
│   │ │   └── concat-map@0.0.1
│   │ ├─┬ once@1.3.3
│   │ │ └── wrappy@1.0.1
│   │ └── path-is-absolute@1.0.0
│   └─┬ mkdirp@0.5.1
│     └── minimist@0.0.8
├── parse5@1.4.2
├── punycode@1.3.2
├── querystring@0.2.0
├── reflect-metadata@0.1.2
├── rxjs@5.0.0-beta.2
├── shelljs@0.5.3
├─┬ tns-core-modules@2.0.0-angular-4
│ └── tns-core-modules-widgets@1.7.0
├── typescript@1.8.10
├── url@0.10.3
└─┬ zone.js@0.5.15
  └── es6-promise@3.1.2
```

### gcc --version
```shell
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks in advance!

**Comment by rosen-vladimirov** [comment]
Hi @leocaseiro ,
This issue is addressed in our release branch and it will be included in the 2.0.0 official release.
You can find more information [here](https://github.com/NativeScript/nativescript-cli/issues/1517) and [here](https://github.com/NativeScript/nativescript-cli/issues/1696)

**Comment by leocaseiro** [comment]
Thank you so much. I've tested now and worked just fine.

PS: I had to update the brew and install my xcode with: `brew install xcproj`

**Comment by leocaseiro** [comment]
Hi @rosen-vladimirov, I'm actually having the same issue still.

I was trying to debug and I've realised that if I comment the `beforewatch/nativescript-dev-typescript.js` reference it works:

_beforewatch/nativescript-dev-typescript.js_
`// module.exports = require("nativescript-dev-typescript/lib/watch.js");`

However, as you can realise, the watch won't work with any JS changes...

I'm not sure how to fix that. Could you please help me out?

_node_modules/nativescript-dev-typescript/lib/watch.js_
```javascript
var compiler = require('./compiler');

module.exports = function ($logger, $projectData, $errors) {
	return compiler.runTypeScriptCompiler($logger, $projectData.projectDir, { watch: true });
}
```

**Comment by leocaseiro** [comment]
> UPDATE

I temporary sorted it out using gulp to watch my .ts files and then, livesync(which works while watching .js files).

In that case, my gulp task watches .ts and update all .js while livesync handles all .js files and update and sync my ios emulator...

**Comment by leocaseiro** [comment]
If someone is interested in this solution:

npm dependencies:
```
npm install --save-dev yargs gulp gulp-load-plugins gulp-plumber gulp-debug gulp-if gulp-typescript gulp-sourcemaps
```

_./gulpfile.js_
```javascript
'use strict';
var args = require('yargs').argv,
    gulp = require('gulp'),
    $ = require('gulp-load-plugins')({lazy: true});

var options = {
    isDebug: args.debug || false,
    isProduction: args.production || false,
    sourceFolder: ['./*.d.ts', './app/**/*.ts'],
    destinationFolder: './app'
};

gulp.task('typescript', function() {
    var tsconfigJson = require('./tsconfig.json');
    return gulp.src(options.sourceFolder)
        .pipe($.plumber())
        .pipe($.if(options.isDebug, $.debug({title: 'typescript'})))
        .pipe($.if(!options.isProduction, $.sourcemaps.init()))
        .pipe($.typescript(tsconfigJson.compilerOptions))
        .pipe($.sourcemaps.write('.'))
        .pipe(gulp.dest(options.destinationFolder));
});

gulp.task('default', ['typescript'], function() {
    gulp.watch(options.sourceFolder, ['typescript']);
});
```

Run with yarg **debug**:

`gulp --debug`

**Comment by leocaseiro** [comment]
Hi, I'd like to reopen this issue and let people know that this problem works on a case-sensitive partition.

I formatted my MAC and I have 2 partitions now, 1 case-sensitive and another one which is not.

The case-sensitive get's the same error, where the case-insensitive runs `livesync` normally.

I believe in somewhere in the code or something with NodeJS perhaps. We have some case-sensitive issue.

I'll investigate and I'll up to date.

**Comment by leocaseiro** [comment]
I've just noticed that the error shows `Error: watch /users/lcaseiro/sites/native-script-groceries ENOENT`

However, my folder structure is: `/Users/lcaseiro/Sites/native-script-groceries`

I'm trying to debug the `addDirWatcher` method which has some inheritance with Nativescript method:
[CompilerHost.useCaseSensitiveFileNames()](https://github.com/NativeScript/xsd-generator/blob/master/customtypings/typescript/typescript.d.ts#L1165)


Any help is very welcome, btw

**Comment by leocaseiro** [comment]
The bus is with TypeScript, not NativeScript.

TypeScript has made some changes with case-sensitive and the solution @cmoffatt found it to Downgrade to TypeScript@1.7.5, you [can read more here](https://github.com/Microsoft/TypeScript/issues/7154):
