### ISSUE TITLE
Cannot run livesync with ios simulator

### ISSUE THREAD

**Issue by dharness** [NativeScript/nativescript-cli#2267]
With a new project created with `tns create app --ng` I am not able to run livesync. Doing so results in the following error:

```
    Error: EEXIST: file already exists, symlink '../semver/bin/semver' -> '/Users/dharness/Library/Developer/CoreSimulator/Devices/232F86F5-B6C1-44AF-A6D5-2936E8A9EAC4/data/Containers/Bundle/Application/6A27D2A5-3E10-4CF7-8F47-E0857AE3476A/sqwakapp.app/app/tns_modules/nativescript-dev-android-snapshot/node_modules/.bin/semver'
```

I've tried deleting the simulator, making new projects, restarting the mac.. to no avail.

EDIT:

I have tried without the --ng flag as well with the same result. I have temporarily gone back to 2.3 to generate my project avoid the issue, and am running it using tns@2.4 cli with no problems.

Of course, i have to temporarily downgrade every time I want to create a new project.

**Comment by indrasantosa** [comment]
+1 here

**Comment by tzraikov** [comment]
@dharness and @indrasantosa We addressed the symlink issue with our latest release 2.4.1. Plase, could you confirm that everything is OK when running this version?

**Comment by indrasantosa** [comment]
Thanks @tzraikov, I have done the fix myself on my local repository, it is now fine :) Cheeer!

**Comment by buzzspaceltd** [comment]
@dharness @tzraikov I am having the same issue.  I just upgraded to 2.4.2 but the issue persists.  Any suggestions on a fix?

**Comment by indrasantosa** [comment]
From what I check, it is due to shelljs copy handles symlink poorly,
upgrading shelljs might help, I think

**Comment by ludwiktrammer** [comment]
I also have the same issue using NativeScript 2.4.2...

**Comment by lukeramsden** [comment]
I'm still getting this error with the latest version `tns update` gives me.

**Comment by vchimev** [comment]
@buzzspaceltd, @ludwiktrammer, @lukeramsden, 

Guys, could you please share exact steps to reproduce along with the `package.json` file of the projects?

I am unable to reproduce this issue with CLI version 2.4.2. CC:// @tzraikov

**Comment by lukeramsden** [comment]
[This is my package.json](https://raw.githubusercontent.com/TissLTD/tiss_mobile/master/package.json). What I do is clone the repo, run `tns install`, then `tns run ios --emulator`, which works fine, then I run `tns livesync ios --emulator --watch` and it gives me this error: 
```
EEXIST: file already exists, symlink '../rimraf/bin.js' -> '/Users/*REDACTED*/Library/Developer/CoreSimulator/Devices/CD80306B-7220-4CFD-BA20-026D12FC73C8/data/Containers/Bundle/Application/F9FCCEC9-F518-4CF5-B949-1D75A6B3A675/tissmobile.app/app/tns_modules/nativescript-i18n/node_modules/fs-extra/node_modules/.bin/rimraf'
```

**Comment by vchimev** [comment]
Thanks a lot, @lukeramsden! I successfully reproduced the shell.js error above.

**Comment by vchimev** [comment]
@lukeramsden, @buzzspaceltd, @ludwiktrammer,

The issue here is that all `.bin` directories inside `node_modules` should be ignored and should not be copied to `platforms` folder.

A temporary workaround is to remove them manually as follows: `find . -iname .bin | xargs rm -rfv`

**Comment by lukeramsden** [comment]
@vchimev Is this going to be fixed in a nativescript-cli updated? Or should I just run this before I try to livesync?

**Comment by vchimev** [comment]
@lukeramsden,

it should be enough to run it only once to clean up the `.bin` directories in `node_modules` and `platforms` folders; than use the `run` and `livesync` commands with no problems.

We are going to fix it for sure in next minor release (2.5.0) this month along with lots of livesync improvements (https://github.com/NativeScript/nativescript-cli/pull/2374); will further investigate if we could provide a patch update (2.4.3) prior that and update this issue if so.

**Comment by lukeramsden** [comment]
@vchimev My suggestion is a `tns clean` command. Maybe you could do `tns clean node` and `tns clean platform` etc

**Comment by vchimev** [comment]
This issue does not exist in *master* branch of NativeScript CLI. It could be installed by:
```
npm i -g nativescript@next
```
