### ISSUE TITLE
Livesync hangs, especially bad on iOS

### ISSUE THREAD

**Issue by vcooley** [NativeScript/nativescript-cli#3235]
I'm having multiple issues with livesync, expecially on iOS. I am unsure if they are related, but I will outline what is happening below.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: `3.3.1`
- Cross-platform modules: `3.3.0`
- Runtime(s): `tns-android: 3.3.1` `tns-ios: 3.3.0`
- Plugin(s):
```
{
    "nativescript-advanced-webview": "^1.1.3",
    "nativescript-angular": "~4.4.1",
    "nativescript-async": "^1.0.2",
    "nativescript-drop-down": "^3.1.0",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-ng-shadow": "^1.1.2",
    "nativescript-plugin-firebase": "^4.0.6",
    "nativescript-pro-ui": "^3.1.3",
    "nativescript-snackbar": "^2.0.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4"
}
```

### Please tell us how to recreate the issue in as much detail as possible.
When I `tns run ios`, my app will begin to build and then hang. Building a clean build seems to temporarily fix it, but eventually it happens again, often in the middle of my day when I haven't made any changes to dependencies or anything like that. I have also noticed that when it is hanging I can suspend the app by pressing the home button and it will proceed. I've seen mentioned to run with the `--log trace` output and I will paste the content below.

```
Loading extensions.
Asserting extension nativescript-angular-cli is installed.
Extension nativescript-angular-cli is installed.
execFile: /Users/vincecooley/Library/Android/sdk/platform-tools/adb "help"
Exec uname -a 
 stdout: Darwin Vinces-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 4.2.0
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Error while executing node-gyp -v: Command failed: node-gyp -v
/bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 9.0.1
Build version 9A1004
 
 stderr: 
Exec gem which xcodeproj 
 stdout: /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.4.2/lib/xcodeproj.rb
 
 stderr: 
Exec pod --version 
 stdout: 1.2.0
 
 stderr: 
Exec '/Users/vincecooley/Library/Android/sdk/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as /Users/vincecooley/Library/Android/sdk/platform-tools/adb

- stderr: 
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Error while executing mono --version: Command failed: mono --version
/bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.13.5 (Apple Git-94)
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: gradle: command not found

Error while executing gradle -v: Command failed: gradle -v
/bin/sh: gradle: command not found

Exec "/Library/Java/Home/bin/javac" -version 
 stdout:  
 stderr: javac 1.8.0_121

System information:
{ procInfo: 'nativescript/3.3.1',
  platform: 'darwin',
  os: 'Darwin Vinces-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v7.9.0',
  npmVer: '4.2.0',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 9.0.1\nBuild version 9A1004\n',
  xcodeprojGemLocation: '/usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.4.2/lib/xcodeproj.rb\n',
  itunesInstalled: true,
  cocoapodVer: '1.2.0',
  adbVer: 'Android Debug Bridge version 1.0.39',
  emulatorInstalled: true,
  monoVer: null,
  gitVer: '2.13.5 (Apple Git-94)',
  gradleVer: null,
  javacVersion: '1.8.0_121' }
Looking for project in '/Users/vincecooley/Projects/myproject'
Project directory is '/Users/vincecooley/Projects/myproject'.
Exec which xcodebuild 
 stdout: /usr/bin/xcodebuild
 
 stderr: 
Exec xcodebuild -version | head -n 1 | sed -e 's/Xcode //' 
 stdout: 9.0.1
 
 stderr: 
Validate options for platform: iOS
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
spawn: node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Searching for devices...
startLookingForDevices; platform is iOS
Starting to look for iOS devices.
Exec ps cax | grep launchd_sim 
 stdout: 23462   ??  S      0:03.01 launchd_sim
 
 stderr: 
Found device with identifier 'BE9FC449-B049-4FF8-967F-23506BE243A7'
startLookingForDevices; platform is iOS
Exec ps cax | grep launchd_sim 
 stdout: 23462   ??  S      0:03.01 launchd_sim
 
 stderr: 
Exec ps cax | grep launchd_sim 
 stdout: 23462   ??  S      0:03.01 launchd_sim
 
 stderr: 
Project dir from hooksArgs is: /Users/vincecooley/Projects/myproject.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/vincecooley/Projects/myproject/hooks' ]
BeforeHookName for command liveSync is before-liveSync
Executing before-liveSync hook from /Users/vincecooley/Projects/myproject/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-liveSync hook at location /Users/vincecooley/Projects/myproject/hooks/before-liveSync/nativescript-angular-sync.js in-process
Validating before-liveSync arguments.
Changes info in prepare platform: ProjectChangesInfo {
  appFilesChanged: false,
  packageChanged: false,
  appResourcesChanged: false,
  nativeChanged: false,
  configChanged: false,
  nativePlatformStatus: '3' }
Skipping prepare.
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'LiveSync',
  label: 'iOS_Simulator_11.0',
  customDimensions: { cd2: 'Angular' } }

```

At this point, I get a hang and can manually suspend the app to resume. I'd also like to note that if I kill it here I get the following message:
```
^CUnable to apply changes on device: BE9FC449-B049-4FF8-967F-23506BE243A7. Error is: process.send is not a function.
Project dir from hooksArgs is: /Users/vincecooley/Projects/myproject.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/vincecooley/Projects/myproject/hooks' ]
AfterHookName for command watch is after-watch
Executing after-watch hook from /Users/vincecooley/Projects/myproject/hooks/after-watch/nativescript-dev-typescript.js
Executing after-watch hook at location /Users/vincecooley/Projects/myproject/hooks/after-watch/nativescript-dev-typescript.js in-process
Validating after-watch arguments.
Project dir from hooksArgs is: /Users/vincecooley/Projects/myproject.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/vincecooley/Projects/myproject/hooks' ]
AfterHookName for command liveSync is after-liveSync
IOSDeviceOperations disposed.
```

Finally, I'm not sure if this is related or not, but I get many incremental compilation messages when I have made no changes. The app does not refresh after receiving these until I have actually made some changes. For example:

```
9:31:38 AM - File change detected. Starting incremental compilation...

9:31:39 AM - Compilation complete. Watching for file changes.

9:31:44 AM - File change detected. Starting incremental compilation...

9:31:45 AM - Compilation complete. Watching for file changes.

9:31:45 AM - File change detected. Starting incremental compilation...

9:31:46 AM - Compilation complete. Watching for file changes.
```
etc...

**Comment by chauhan-saurabh** [comment]
same issue

**Comment by NickIliev** [comment]
Hey, @vcooley  @chauhan-saurabh can you guys test the `run` command (livesync) with iOS 10 (instead of iOS 11) - we are currently investigating this issue and on our side, it seems related to the latest iOS version.

Please do let me know if you are experiencing the same trouble when using iOS 10 emulators

**Comment by vcooley** [comment]
I'm still getting the same problem, though so far I have not had multiple incremental compilation messages when I have made no changes. 

What I am experiencing is the livesync working after multiple changes and multiple saves. So far it has required me to make two changes for the app to refresh. Here's an example of the output where I saved a change, waited ~30 seconds and saved another change.

```
10:07:12 AM - File change detected. Starting incremental compilation...



10:07:12 AM - Compilation complete. Watching for file changes.



10:07:46 AM - File change detected. Starting incremental compilation...



10:07:46 AM - Compilation complete. Watching for file changes.



Executing before-prepare hook from /Users/vincecooley/Projects/myproject/hooks/before-prepare/nativescript-dev-typescript.js
Executing before-prepare hook from /Users/vincecooley/Projects/myproject/hooks/before-prepare/nativescript-plugin-firebase.js
Preparing project...
Project successfully prepared (iOS)
Executing after-prepare hook from /Users/vincecooley/Projects/myproject/hooks/after-prepare/firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from /Users/vincecooley/Projects/myproject/hooks/after-prepare/firebase-copy-google-services.js
Executing after-prepare hook from /Users/vincecooley/Projects/myproject/hooks/after-prepare/nativescript-plugin-firebase.js
Executing after-prepare hook from /Users/vincecooley/Projects/myproject/hooks/after-prepare/nativescript-unit-test-runner.js
Successfully transferred payment.service.js.
Successfully transferred payment.service.ts.
Successfully transferred payment.service.ts.
Successfully transferred payment.service.js.
Refreshing application...
```

**Comment by dtopuzov** [comment]
I was able to reproduce similar issue only on iOS11 simulator with following steps:
- Create brand new JS project and open it with VSCode 
- Create new folder and text file inside
- Copy the folder
=> Livesync process to not exit, but not changes are applied on the simulator.

**Comment by chauhan-saurabh** [comment]
Hey @NickIliev yes tns run ios (livesync) work fines on iOS 10

**Comment by dtopuzov** [comment]
Hack for iOS11 issue: 
After clicking on the home button of the simulator (to mimimize the app) changes are synced.

**Comment by thaoula** [comment]
Hi @dtopuzov,

Any timeline for fixing this ... pretty much have to kill IOS livesync every one or two changes.

Regards,
Tarek

**Comment by rosen-vladimirov** [comment]
Hey @thaoula,
Can you please send us your steps to reproduce, so we can take a look at all cases. Also it will be a great help in case you can send us your package.json file, so we can use the same dependencies and devDependencies while investigating the issue.

**Comment by Fatme** [comment]
Hey guys,

I've investigated the issue and found that {N} CLI hangs when trying to start the application. It seems that **simctl launch** command does not launch the process immediately and we have to wait a little bit, just to ensure all related processes and services are alive. I'm trying to fix the problem with above PR.

**Comment by thaoula** [comment]
Hi @Fatme,

Steps for me are the same. 

1. Start App tns debug ios
2. Make changes (App updates)
3. Make changes (repeat 1 or two more times).
4. Now app does not refresh and pressing ctrl-c does cannot terminate the process anymore.

I have recently switched to @next builds and using tns debug ios --bundle to use the webpack approach which seems much more stable although i cannot debug and it a little slower.

Regards,
Tarek

**Comment by dtopuzov** [comment]
Fixed in 4.0rc

**Comment by vultix** [comment]
@dtopuzov I am still seeing this issue in 4.0.0.  

Same steps for reproduction:
1. Start with tns debug ios
2. Make changes to trigger app update
3. Repeat 
4. App doesn't refresh, ctrl-c doesn't work.

The only error message I see in the output is this:

`Unable to apply changes on device: 986FF637-664E-4C90-8CF5-518D50BDFA5D. Error is: process.send is not a function.`

`$tns --version: 4.0.0`

```
Package.json dependencies:
"nativescript": {
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.0"
    }
  }
"dependencies": { 
    "nativescript-angular": "^5.3.0",
    "nativescript-background-http": "^3.2.1",
    "nativescript-fresco": "^3.0.6",
    "nativescript-imagepicker": "^5.0.0",
    "nativescript-iqkeyboardmanager": "^1.2.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-pulltorefresh": "^2.1.0",
    "nativescript-social-share": "^1.5.0",
    "nativescript-socket.io": "0.9.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-autocomplete": "^3.6.0",
    "nativescript-ui-listview": "^3.5.4"
    // Dev dependencies
    "nativescript-css-loader": "^0.26.0",
    "nativescript-dev-sass": "^1.5.0",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "^0.8.1",
}

```

**Comment by Fatme** [comment]
Hi @vultix,

Execute `xcrun simctl list devices` command and send us the output. Seems your build tools are not configured correctly.

**Comment by vultix** [comment]
@Fatme I updated to the latest version of XCode and downloaded the IOS 10.3 simulators in my attempts to get debugging working, I'm not sure if that changes the following:

```
== Devices ==
-- iOS 10.3 --
    iPhone 5 (7897CA7E-2DBC-4C8B-A63A-917683C1B85E) (Shutdown)
    iPhone 5s (A74844CE-DAED-4289-AC06-AF4B563005B9) (Shutdown)
    iPhone 6 (F83D7B74-975B-4C99-9996-8F2842503688) (Shutdown)
    iPhone 6 Plus (06DC401B-D0C8-440C-8853-A8FCC312BF8C) (Shutdown)
    iPhone 6s (97ABFB11-1F08-4AA5-84FE-19D627EE2CE1) (Shutdown)
    iPhone 6s Plus (F0772B29-65B4-4F32-8D11-52467B7C30BE) (Shutdown)
    iPhone 7 (D2F61D12-AA24-45A1-A7B8-1C6BD44523F7) (Shutdown)
    iPhone 7 Plus (90D93893-73EB-48D4-A5D4-9DE19E1F663D) (Shutdown)
    iPhone SE (6EBC39FF-3B27-4DA5-BC63-9E23E54BB7FF) (Shutdown)
    iPad Air (1B65E2EC-B355-4186-888D-BB5C21527EFA) (Shutdown)
    iPad Air 2 (200B809D-1FA6-49A0-8957-68FB96BCE9D0) (Shutdown)
    iPad (5th generation) (AC66C954-8524-4E68-B5CA-D1D7F746BCD5) (Shutdown)
    iPad Pro (9.7 inch) (5F5EF020-FA98-4A7B-B737-24018AF05C66) (Shutdown)
    iPad Pro (12.9 inch) (2BA28418-007D-4BF3-9B14-23DBBED1BA3A) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (E9016E25-B501-44D7-B29E-7C034DA12E9C) (Shutdown)
    iPad Pro (10.5-inch) (CFBF936B-8498-41FC-BF38-CDDAF810DB94) (Shutdown)
-- iOS 11.2 --
    iPhone 5s (618222DE-FE5B-4A0E-BE15-2B07CF6A6740) (Shutdown)
    iPhone 6 (ECC49556-53C0-4B95-9DD6-F0E67EE46F0E) (Shutdown)
    iPhone 6 Plus (2D89551B-596C-4239-8CD2-C7BDD99C4EEF) (Shutdown)
    iPhone 6s (F84FFE3F-6C23-4282-976F-C3C48B3E80A4) (Shutdown)
    iPhone 6s Plus (922FDB52-CCAC-40BA-8838-3BB25BC07459) (Shutdown)
    iPhone 7 (45066040-E594-47AE-8927-4B6D2BF7B78F) (Shutdown)
    iPhone 7 Plus (2BE5BB1D-36AC-4100-B4CC-85CCCDE2345F) (Shutdown)
    iPhone 8 (D0C3078D-1EED-49D2-8B8C-AAF7B8C01EBE) (Shutdown)
    iPhone 8 Plus (9833509C-D0DA-4D77-8E9B-519F718037CF) (Shutdown)
    iPhone SE (E1446601-F005-4576-8FC1-52598B508387) (Shutdown)
    iPhone X (6441785F-93B7-4736-955A-BF5EBD502A4D) (Shutdown)
    iPad Air (1C02A327-E042-4903-A05B-A4963F1BAA38) (Shutdown)
    iPad Air 2 (A11E27D3-AE05-4041-A0C7-63B44B9249C9) (Shutdown)
    iPad (5th generation) (4072F575-028C-41B0-A603-8D266DFC0673) (Shutdown)
    iPad Pro (9.7-inch) (E8AEBC39-38DF-4076-B6A2-771536C71AEA) (Shutdown)
    iPad Pro (12.9-inch) (D3676A3E-48EA-4151-A666-9D626A554504) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (C186538B-94B6-499B-814C-3B52C316AA35) (Shutdown)
    iPad Pro (10.5-inch) (B26988C9-45AA-412A-805E-19E9050336BB) (Shutdown)
```

**Comment by Fatme** [comment]
Hi @vultix,

In case when xCode is updated or new sdk is added, sometimes native build tools are not fully configured and some different errors can happen.

Sometimes executing `xcrun simctl list devices` fixes the configuration. As I can see the result from `xcrun simctl list devices` command is correct, so please can you try to execute `tns debug` command now.

**Comment by vultix** [comment]
@Fatme, Thank you for your help.

I am still seeing the same issue.  Both on ios 10 and ios 11 simulators.

**Comment by Fatme** [comment]
Hi @vultix,

Sorry to hear that. Another thing you can try is to run your native project from xcode. In case you still have some configuration issue, this should fix it.

1. Go to your project directory
2. Go to platforms/ios folder
3. Open `.xcodeproj` with xcode.
4. Run the application from xcode.
5. After the application ran, stop it.

After that try to execute `tns debug` command again.

**Comment by Fatme** [comment]
If the above suggestion does not fix your issue and the error is still reproduced, can you please execute `tns debug ios --log trace` command and send us the output.

**Comment by vultix** [comment]
@Fatme sorry for the delayed response.  I am still seeing the same issue after trying your fix.

The build freezes after the `Skipping prepare.` message.  I have to manually press ctrl-c to stop it.  That is when I get the error message. 

Here is the output from the `tns debug ios --log trace` command.

```
Loading extensions.
Asserting extension nativescript-cloud is installed.
Extension nativescript-cloud is installed.
Asserting extension nativescript-starter-kits is installed.
Extension nativescript-starter-kits is installed.
System information:
{ platform: 'darwin',
  shell: '/bin/bash',
  os: 'Darwin Aidans-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64\n',
  procArch: 'x64',
  nodeVer: '9.9.0',
  npmVer: '5.6.0',
  nodeGypVer: null,
  nativeScriptCliVersion: '4.0.0',
  gitVer: '2.11.1',
  dotNetVer: null,
  javacVersion: '1.8.0_74',
  adbVer: '1.0.39',
  androidInstalled: true,
  monoVer: '4.8.0',
  gradleVer: null,
  isAndroidSdkConfiguredCorrectly: true,
  xcodeVer: '9.2.0',
  xcodeprojLocation: '/usr/local/bin/xcodeproj',
  itunesInstalled: true,
  cocoaPodsVer: '1.2.1',
  isCocoaPodsWorkingCorrectly: true,
  isCocoaPodsUpdateRequired: false,
  pythonInfo: { isInstalled: true, isSixPackageInstalled: true } }
Looking for project in '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile'
Project directory is '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile'.
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: {} }
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
spawn: node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
CocoaPods are installed.
CocoaPods update is not required.
CocoaPods are configured properly.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: true',
  customDimensions: {} }
Exec xcodebuild -version | head -n 1 | sed -e 's/Xcode //' 
 stdout: 9.2
 
 stderr: 
Searching for devices...
startLookingForDevices; platform is iOS
Starting to look for iOS devices.
Found device with identifier '6441785F-93B7-4736-955A-BF5EBD502A4D'
startLookingForDevices; platform is iOS
Validate options for platform: iOS
Project dir from hooksArgs is: /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks' ]
BeforeHookName for command liveSync is before-liveSync
Executing before-liveSync hook from /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-liveSync hook at location /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/before-liveSync/nativescript-angular-sync.js in-process
Validating before-liveSync arguments.
Changes info in prepare platform: ProjectChangesInfo {
  appFilesChanged: false,
  packageChanged: false,
  appResourcesChanged: false,
  nativeChanged: false,
  configChanged: false,
  nativePlatformStatus: '3' }
Project dir from hooksArgs is: /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks' ]
BeforeHookName for command shouldPrepare is before-shouldPrepare
Project dir from hooksArgs is: /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks' ]
AfterHookName for command shouldPrepare is after-shouldPrepare
Skipping prepare.
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'LiveSync',
  label: 'iOS_Simulator_11.2',
  customDimensions: { cd2: 'Angular' } }
^[b^[b^CUnable to apply changes on device: 6441785F-93B7-4736-955A-BF5EBD502A4D. Error is: process.send is not a function.
Project dir from hooksArgs is: /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks' ]
AfterHookName for command watch is after-watch
Executing after-watch hook from /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/after-watch/nativescript-dev-sass.js
Executing after-watch hook at location /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/after-watch/nativescript-dev-sass.js in-process
Validating after-watch arguments.
Executing after-watch hook from /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/after-watch/nativescript-dev-typescript.js
Executing after-watch hook at location /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks/after-watch/nativescript-dev-typescript.js in-process
Validating after-watch arguments.
Project dir from hooksArgs is: /Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile.
Hooks directories: [ '/usr/local/lib/node_modules/nativescript/lib/hooks',
  '/usr/local/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/aidan/dev/workspaces/SnowyOwlGlobal/apps/mobile/hooks' ]
AfterHookName for command liveSync is after-liveSync
IOSDeviceOperations disposed.
```

**Comment by dtopuzov** [comment]
Hi @vultix 

The original issue is reallt

**Comment by EmandM** [comment]
I'm hitting an issue on OS X where the livesync freezes randomly. If I hit ctrl+c at this point, it seems to unfreeze and gives this error:
`Unable to apply changes for device. Error is: process.send is not a function.`

I have only seen this issue so far on iOS 11, thought I haven't tried running on iOS 10.

**Comment by jnorkus** [comment]
Same issue. After it happens the only way I found to get it working again is `rm -rf platforms`, otherwise it freezes every time.

**Comment by torabian** [comment]
> Hi @dtopuzov,
> 
> Any timeline for fixing this ... pretty much have to kill IOS livesync every one or two changes.
> 
> Regards,
> Tarek

This solves but sucks dude!

**Comment by chrillewoodz** [comment]
When using `nativescript-angular` it gets stuck a lot after the `Webpack build done!` message, at that point I have to close the app manually in the emulator, kill the process and re-run `npm run ios`. Very annoying.

**Comment by dottodot** [comment]
Trying to livesync on an ios device is pretty much impossible I get a successful sync maybe 1 in 10 trys if I'm lucky, not such problems on the simulator. Most of the time it gives a Successfully synced application message even when it hasn't refreshed. The other times it gets to the launch screen and becomes completely stuck. If I try and close the app it just launches itself again and gets stuck at the same place the only thing that can be done is to reboot the device.

Seems like removing the platform folder does clear this issue until the next time, but that's not really ideal.

**Comment by endarova** [comment]
Hi @dottodot,
I am not able to reproduce the issues you are describing with the latest version of the cli(5.2.0). In order to investigate this behavior we will need more information.  Can you please provide:
1. CLI version you are using.
2. Project details: What kind of project (JS, Angular, etc.) , project's package.json content . If possible you can send us a sample application with which you reproduce the issue.
3. Logs of the command you execute. For example: 'tns run ios --log trace >log.txt'

**Comment by Fatme** [comment]
Closing due to inactivity.
