### ISSUE TITLE
Podfile generation broken on livesync

### ISSUE THREAD

**Issue by vcooley** [NativeScript/nativescript-cli#3549]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0 
- Cross-platform modules: 4.0.0
- Runtime(s): 4.0.1
- Plugin(s): 
```
    "nativescript-advanced-webview": "^1.1.3",
    "nativescript-angular": "~5.3.0",
    "nativescript-async": "^1.0.2",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-directions": "^1.2.0",
    "nativescript-drop-down": "^3.2.4",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-input-mask": "^1.0.0",
    "nativescript-iqkeyboardmanager": "~1.1.0",
    "nativescript-ng-shadow": "^2.0.0",
    "nativescript-plugin-firebase": "^5.3.0",
    "nativescript-pro-ui": "^3.3.0",
    "nativescript-snackbar": "^2.0.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
```

### Please tell us how to recreate the issue in as much detail as possible.
Running `tns run ios --clean` with this configuration produces a working build, however any changes made to the code cause the Podfile to be rebuilt in a way that causes a recursion error.

Here is my Podfile (from `platforms/ios`) after the initial build:
```
use_frameworks!

target "myproject" do
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install1 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-floatingactionbutton/platforms/ios/Podfile 
 pod 'MNFloatingActionButton', '~> 0.1.5' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-google-maps-sdk/platforms/ios/Podfile 
 source 'https://github.com/CocoaPods/Specs.git'

pod 'GoogleMaps' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-input-mask/platforms/ios/Podfile 
 pod 'InputMask', :path => '~/Projects/input-mask-ios'

def post_install2 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager', '~> 4.0.0'
 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile 
 pod 'Firebase', '~> 4.11.0' 
pod 'Firebase/Auth'

# Uncomment if you want to enable Realtime DB
pod 'Firebase/Database'

# Uncomment if you want to enable Cloud Firestore
pod 'Firebase/Firestore'

# Uncomment if you want to enable Remote Config
#pod 'Firebase/RemoteConfig'

# Uncomment if you want to enable Crash Reporting
#pod 'Firebase/Crash'

# Uncomment if you want to enable Crashlytics
pod 'Fabric'
pod 'Crashlytics'
# Crashlytics works best without bitcode
def post_install3 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end

# Uncomment if you want to enable FCM (Firebase Cloud Messaging)
#pod 'Firebase/Messaging'

# Uncomment if you want to enable Firebase Storage
#pod 'Firebase/Storage'

# Uncomment if you want to enable AdMob
#pod 'Firebase/AdMob'

# Uncomment if you want to enable Invites and/or Dynamic Links
#pod 'Firebase/Invites'

# Uncomment if you want to enable Facebook Authentication
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'

# Uncomment if you want to enable Google Authentication
#pod 'GoogleSignIn' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-snackbar/platforms/ios/Podfile 
 pod 'SSSnackbar', :git => 'https://github.com/EddyVerbruggen/SSSnackbar.git', :tag => '0.1.2.4' 
 # End Podfile 

end
post_install do |installer|
  post_install1 installer
  post_install2 installer
  post_install3 installer
end
```

And here is my Podfile after making a change within my application's code. The problem occurs in the `post_install1` method, which recursively calls itself, but the entire Podfile is mangled:
```
use_frameworks!

target "myproject" do
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install1 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-floatingactionbutton/platforms/ios/Podfile 
 pod 'MNFloatingActionButton', '~> 0.1.5' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-google-maps-sdk/platforms/ios/Podfile 
 source 'https://github.com/CocoaPods/Specs.git'

pod 'GoogleMaps' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-input-mask/platforms/ios/Podfile 
 pod 'InputMask', :path => '~/Projects/input-mask-ios'

def post_install2 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager', '~> 4.0.0'
 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile 
 pod 'Firebase', '~> 4.11.0' 
pod 'Firebase/Auth'

# Uncomment if you want to enable Realtime DB
pod 'Firebase/Database'

# Uncomment if you want to enable Cloud Firestore
pod 'Firebase/Firestore'

# Uncomment if you want to enable Remote Config
#pod 'Firebase/RemoteConfig'

# Uncomment if you want to enable Crash Reporting
#pod 'Firebase/Crash'

# Uncomment if you want to enable Crashlytics
pod 'Fabric'
pod 'Crashlytics'
# Crashlytics works best without bitcode
def post_install3 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end

# Uncomment if you want to enable FCM (Firebase Cloud Messaging)
#pod 'Firebase/Messaging'

# Uncomment if you want to enable Firebase Storage
#pod 'Firebase/Storage'

# Uncomment if you want to enable AdMob
#pod 'Firebase/AdMob'

# Uncomment if you want to enable Invites and/or Dynamic Links
#pod 'Firebase/Invites'

# Uncomment if you want to enable Facebook Authentication
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'

# Uncomment if you want to enable Google Authentication
#pod 'GoogleSignIn' 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-snackbar/platforms/ios/Podfile 
 pod 'SSSnackbar', :git => 'https://github.com/EddyVerbruggen/SSSnackbar.git', :tag => '0.1.2.4' 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-input-mask/platforms/ios/Podfile 
 pod 'InputMask', :path => '~/Projects/input-mask-ios'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end 
 # End Podfile 
# Begin Podfile - /Users/vincecooley/Projects/myproject/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile 
 pod 'Firebase', '~> 4.11.0' 
pod 'Firebase/Auth'

# Uncomment if you want to enable Realtime DB
pod 'Firebase/Database'

# Uncomment if you want to enable Cloud Firestore
pod 'Firebase/Firestore'

# Uncomment if you want to enable Remote Config
#pod 'Firebase/RemoteConfig'

# Uncomment if you want to enable Crash Reporting
#pod 'Firebase/Crash'

# Uncomment if you want to enable Crashlytics
pod 'Fabric'
pod 'Crashlytics'
# Crashlytics works best without bitcode
def post_install4 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end

# Uncomment if you want to enable FCM (Firebase Cloud Messaging)
#pod 'Firebase/Messaging'

# Uncomment if you want to enable Firebase Storage
#pod 'Firebase/Storage'

# Uncomment if you want to enable AdMob
#pod 'Firebase/AdMob'

# Uncomment if you want to enable Invites and/or Dynamic Links
#pod 'Firebase/Invites'

# Uncomment if you want to enable Facebook Authentication
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'

# Uncomment if you want to enable Google Authentication
#pod 'GoogleSignIn' 
 # End Podfile 

end
post_install do |installer|
  post_install1 installer
  post_install2 installer
  post_install3 installer
  post_install4 installer
end
```

**Comment by speigg** [comment]
My pod file keeps getting messed up as well. Increasingly so every time I try to build.

**Comment by NathanWalker** [comment]
@rosen-vladimirov If you have some a branch in progress perhaps could post it and reference this issue just so others can see movement here as it's big issue affecting many at moment.

**Comment by rosen-vladimirov** [comment]
Hey guys, we've investigated this issue and I confirm the unexpected behavior. It can be easily reproduced by executing the following commands:
```
$ tns create myApp
$ cd myApp
$ tns plugin add nativescript-input-mask
$ tns plugin add nativescript-bottombar
$ tns run ios
$ tns run ios
```

We are working on a fix and I'll write back once we have more information.

**Comment by rosen-vladimirov** [comment]
Hey @noumaans ,
Can you please post your package.json as well, so we can investigate this scenario as well. Currently I've noticed the problem occurs when several of the plugins have postinstall scripts and also when CLI tries to prepare the plugins several times. The steps I've described include the `nativescript-input-mask` plugin, which currently has issue with its Podfile (I've logged an issue here: https://github.com/vcooley/nativescript-input-mask/issues/2). In case all plugins have correct Podfiles, CLI should be able to handle them correctly at least in incremental builds, i.e. when the preparation of the plugins is skipped.

**Comment by noumaans** [comment]
@rosen-vladimirov 
```
$ grep nativescript package.json 
  "nativescript": {
    "nativescript-angular": "^5.3.0",
    "nativescript-appavailability": "^1.3.1",
    "nativescript-appversion": "^1.4.1",
    "nativescript-bottombar": "^3.0.8",
    "nativescript-carousel": "^3.1.0",
    "nativescript-directions": "^1.2.0",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-gradient": "^2.0.1",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-ngx-fonticon": "4.1.0",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "^6.0.2",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-dataform": "^3.6.0",
    "nativescript-ui-listview": "^3.5.7",
    "nativescript-web-image-cache": "^4.2.4",
    "nativescript-css-loader": "^0.26.1",
    "nativescript-dev-appium": "^3.3.0",
    "nativescript-dev-sass": "^1.5.0",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-worker-loader": "~0.8.1",
```

**Comment by nicHoch** [comment]
same for me:
```

		"nativescript-appversion": "~1.4.1",
		"nativescript-bitmap-factory": "^1.7.1",
		"nativescript-bottom-navigation": "^1.2.0",
		"nativescript-clipboard": "^1.1.7",
		"nativescript-directions": "^1.0.5",
		"nativescript-dom": "^2.0.0",
		"nativescript-feedback": "^1.1.2",
		"nativescript-geolocation": "^3.0.0",
		"nativescript-google-maps-sdk": "^2.6.0",
		"nativescript-iqkeyboardmanager": "^1.3.0",
		"nativescript-master-technology": "^1.1.1",
		"nativescript-orientation": "^1.6.1",
		"nativescript-permissions": "^1.2.3",
		"nativescript-plugin-firebase": "^5.3.1",
		"nativescript-pro-ui": "^3.2.0",
		"nativescript-pulltorefresh": "^2.1.1",
		"nativescript-screenshot": "0.0.2",
		"nativescript-slides": "^2.2.12",
		"nativescript-social-login": "^4.0.1",
		"nativescript-sqlite": "^2.0.1",
		"nativescript-theme-core": "^1.0.4",
		"nativescript-webview-interface": "^1.4.2",
```
```

✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.0 version and is up to date.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
✔ Component tns-android has 4.1.2 version and is up to date.
✔ Component tns-ios has 4.1.0 version and is up to da
```te.

**Comment by vcooley** [comment]
I've done some investigation today. I've found that this problem is caused with certain combinations of plugins with Podfiles. For instance when I remove **either** `nativescript-input-mask` or `nativescript-bottombar` from my package and node_modules everything seems to work as expected.

I'm working on the issue mentioned by @rosen-vladimirov above. However in the meantime if you need to use the `nativescript-input-mask` plugin you can drop this unzip the dependency to `~/Projects/input-mask-ios`.
[input-mask-ios.zip](https://github.com/NativeScript/nativescript-cli/files/2095737/input-mask-ios.zip)

**Comment by rosen-vladimirov** [comment]
Hey @vcooley , the issue is in CLI when regenerating the Podfile and I'm working on a fix. We'll do our best to release it in one of the next patches release of NativeScript CLI.

**Comment by NathanWalker** [comment]
`npm i -g nativescript@next` fixes this issue 👍

Thanks for the fix.

**Comment by rosen-vladimirov** [comment]
Hey @NathanWalker ,
Thanks to @sis0k0  we have fixed the case when `--bundle` is passed in the `next` version of CLI. The full fix for the Podfile regeneration will be included in 4.2.0. Thanks for your patience and cooperation.

**Comment by NathanWalker** [comment]
The issue has surfaced again on iOS. disregard `next` - still an issue.

**Comment by NathanaelA** [comment]
I just want to make sure I understand correctly; and that you have covered a corner case that I have ran into on both iOS and Android...  Since my case doesn't have the `--bundle` flag attached to it...

I use plain NativeScript for most my projects (not Vue or Angular).  So I don't use the `--bundle` command.  However, if I am working on a plugin (which I've done several this month) for a client I will use the `--syncAllFiles` on the demo app.    

I have noticed several times:
1. A TS, JS, CSS, XML file change will almost always rebuild the app if the plugin has a AAR, Podfile, or Gradle file, even if nothing changed in the plugins `platforms/` folder.  (This rebuild eats a lot of time)

2. A TS, JS, CSS, XML file change will occasionally rebuild the app on iOS even without a platforms/ios folder.   Not sure the trigger; but occasionally it decides it want's to rebuild it again, rather than just livesync'g the single changed file over.   (This rebuild is just plain annoying!)

**Comment by rosen-vladimirov** [comment]
Hey @NathanaelA , the mentioned PR should fix exactly this behavior - no matter if you pass `--syncAllFiles` or not, CLI should not reprepare native parts of plugins in case they are not changed. That's what the PR fixes as behavior. It will soon land in the `next`, so you'll be able to give it a try.

**Comment by rosen-vladimirov** [comment]
So @NathanaelA , @NathanWalker  - the fix is in master branch and in CLI's next version. Can you give it a try and see if it resolves your issue?

**Comment by DickSmith** [comment]
Hey @rosen-vladimirov,

I can confirm `nativescript@next` is working for the project @NathanWalker has been referring too. Both with and without `--syncAllFiles`.

Thanks again. :D

**Comment by NathanWalker** [comment]
Nice work @rosen-vladimirov 🙌 ❤️
