### ISSUE TITLE
App with lazily loaded module fails with tns preview --bundle

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4128]
@isc30 commented on [Sun Nov 11 2018](https://github.com/NativeScript/NativeScript/issues/6545)

**Environment**

    √ Component nativescript has 5.0.0 version and is up to date.
    √ Component tns-core-modules has 5.0.2 version and is up to date.
    √ Component tns-android has 5.0.0 version and is up to date.
    √ Component tns-ios has 5.0.0 version and is up to date.

**Describe the bug**
Current version of [Template Drawer Navigation (Angular)](https://github.com/NativeScript/template-drawer-navigation-ng) doesn't work well when running `tns preview --bundle`.

    Error: com.tns.NativeScriptException: Failed to find module: "~/app/home/home.module", relative to: /app/

**To Reproduce**
Start a new project from the template and run `tns preview --bundle`

**Expected behavior**
It should run properly. With `tns preview` it works well, so its related to webpack.

---

@Fatme commented on [Mon Nov 12 2018](https://github.com/NativeScript/NativeScript/issues/6545#issuecomment-437780791)

@isc30,

Currently preview app has a limitation and does not support lazy loading with angular projects.

The error you receive is due to the fact that `home` module is lazy loaded here https://github.com/NativeScript/template-drawer-navigation-ng/blob/master/src/app/home/home-routing.module.ts#L12. If you want to run `preview --bundle` command with `drawer navigation` template, you need to refactor all places where lazy loading is used.

The another option is to create an application from `tabs` or `hello world` templates. These templates do not have lazy loading, so they will work automatically with `tns preview --bundle` command.

---

@isc30 commented on [Mon Nov 12 2018](https://github.com/NativeScript/NativeScript/issues/6545#issuecomment-437882462)

Lazy loading also prevents HMR, right?
Is it recommended to avoid lazy loading for now and take advantage of bundling and HMR? What's the best approach for the future?
Thanks a lot @fatme

**Comment by jbarnabe** [comment]
Hi @NickIliev, any news about this ? it's very impacting for ios development on windows even if the lazy loading is bypassable.

**Comment by DimitarTachev** [comment]
Hi @jbarnabe, this issue should be fixed in the latest (`0.19.0`) version of the `nativescript-dev-webpack` plugin. The app templates are also updated with the latest webpack plugin. You could create a new app from the SideDrawer template and try to preview it with bundle.

**Comment by jbarnabe** [comment]
Hi @DimitarTachev, very good news, thx for the info and the fix !

**Comment by letsgoforaride** [comment]
Hey, for me updating to 0.19.0 did not solve the issue with lazy loaded modules. Do I need to update more packages?

**Comment by jbarnabe** [comment]
Hi @letsgoforaride, on what platform are you testing on? It seems to work for me on iOS preview app but not on Android preview app with nativescript-dev-webpack 0.9.0

**Comment by Fatme** [comment]
@letsgoforaride,

You need to ensure you're using `nativescript-dev-webpack@0.19.0` or newer version and need to ensure you updated your `webpack.config` file.
In order to update your `webpack.config` file you can use the following command:
```
./node_modules/.bin/update-ns-webpack --configs
```

**Comment by letsgoforaride** [comment]
Update webpack.config file was what I needed to do yet. Thank you for help
