### ISSUE TITLE
tns update ios  is not working

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4681]
- CLI: 5.4.0

Steps:
1. tns create MyApp --js
2. tns platform add ios@5.0.0
3. tns platform update ios

Expected: platform ios to be updated to latest version
Actual: Command fails with message:
The content of the current project file: /TestProjects/n12/platforms/ios/n12.xcodeproj/project.pbxproj and the new project file: /var/folders/qf/619q3nkx0fx88gd52_ffmz8hxrr56w/T/runtime-to-update11955-21364-1uegwr7.hyog/framework/__PROJECT_NAME__.xcodeproj/project.pbxproj is different.
Native Platform cannot be updated.

**Comment by paxperscientiam** [comment]
Confirming same experience on Catalina.

**Comment by paxperscientiam** [comment]
@miroslavaivanova am i missing something? this is still a problem in version 6.1.2

**Comment by DimitarTachev** [comment]
Hi @paxperscientiam,

The fix is available in the `next` version of the CLI (`npm i nativescript@next`) and will be officially released in NativeScript@6.2.0 in a few weeks.

**Comment by paxperscientiam** [comment]
@DimitarTachev thanks a lot for the update. For posterity, I'll note that the tried and true approach of removing and re-adding the platform worked for me.

**Comment by kryptus36** [comment]
I just closed my duplicate bug, but I'm still seeing this error in my project after upgrading to 6.3.0-2019-10-31-115648-13974

As noted in my other bug, deleting platforms does not fix in my case.

**Comment by kryptus36** [comment]
Fixed: I had to run 

`npm i -g nativescript@next`

Note the global flag as opposed to above
