### ISSUE TITLE
error: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')  ** BUILD FAILED **  Command xcodebuild failed with exit code 65

### ISSUE THREAD

**Issue by dasarijit88** [NativeScript/nativescript-cli#5449]
I have been getting the below error everytime i try to run . Can someone please help. I am attaching the logtrace below for further investigation

Arijits-Mac-mini:test arijitdas$ tns run ios --log trace

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*                                                                                                                                               *
*  The "TRACE" log level might print some sensitive data like secrets or access tokens in request URLs. Be careful when you share this output.  *
*                                                                                                                                               *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini 
 stdout: Software:

    System Software Overview:

      System Version: macOS 11.1 (20C69)
      Kernel Version: Darwin 20.2.0
      Time since boot: 18 minutes

 
 stderr: 
macOS version based on system_profiler is 11.1.
Looking for project in '/Users/arijitdas/Autility/Repository/test'
Project directory is '/Users/arijitdas/Autility/Repository/test'.
Loading extensions.
System information:
{
  "platform": "darwin",
  "shell": "/bin/bash",
  "os": "Darwin Arijits-Mac-mini.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 x86_64\n",
  "procArch": "x64",
  "nodeVer": "14.15.1",
  "npmVer": "6.14.8",
  "nodeGypVer": null,
  "nativeScriptCliVersion": "6.7.4",
  "gitVer": "2.24.3 (Apple Git-128)",
  "dotNetVer": null,
  "javacVersion": null,
  "javaVersion": "15.0.1",
  "javaPath": "java",
  "adbVer": "1.0.41",
  "androidInstalled": true,
  "monoVer": null,
  "gradleVer": null,
  "isAndroidSdkConfiguredCorrectly": true,
  "xcodeVer": "12.3.0",
  "xcodeprojLocation": "/usr/local/bin/xcodeproj",
  "itunesInstalled": false,
  "cocoaPodsVer": "1.10.0",
  "isCocoaPodsWorkingCorrectly": true,
  "isCocoaPodsUpdateRequired": false,
  "pythonInfo": {
    "isInstalled": true,
    "isSixPackageInstalled": true
  }
}
Current CLI version:  6.7.4
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command resolveCommand is before-resolveCommand
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command resolveCommand is after-resolveCommand
Trying to handle SIGINT event. CLI overrides this behavior and does not allow handling SIGINT as this causes issues with Ctrl + C in terminal.
The stackTrace of the location trying to handle SIGINT is:
    at process.on (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:24:28)
    at /usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:122:15
    at Array.filter (<anonymous>)
    at load (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:120:21)
    at module.exports (/usr/local/lib/node_modules/nativescript/node_modules/signal-exit/index.js:35:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/lib/lockfile.js:296:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/proper-lockfile/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/detached-processes/cleanup-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Shasum of file /Users/arijitdas/Autility/Repository/test/package.json is 91beb1f6ad9f04e852308b01295d9de6a50e42cc
Got cached result for shouldMigrate for platform: iOS
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command checkEnvironment is before-checkEnvironment
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'enabled', TrackExceptions: 'enabled' }
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Starting',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/lib/services/analytics/analytics-broker-process.js" "/usr/local/lib/node_modules/nativescript/lib/bootstrap.js"
Error while trying to parseJson  data from /Users/arijitdas/.local/share/.nativescript-cli/doctor-cache.json file. Err is: SyntaxError: Unexpected end of JSON input
getInfos cacheConfig options: { forceCheck: undefined }  current info from cache:  null
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
CocoaPods are installed.
CocoaPods update is not required.
CocoaPods are configured properly.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Xcode version 12.3.0 satisfies minimum required version 10.
Error while trying to parseJson  data from /Users/arijitdas/.local/share/.nativescript-cli/doctor-cache.json file. Err is: SyntaxError: Unexpected end of JSON input
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Check Local Build Setup',
  label: 'Finished: Is setup correct: true',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command checkEnvironment is after-checkEnvironment
Validate options for platform: iOS
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'pageview',
  path: 'run ios',
  title: 'run ios',
  customDimensions: { cd5: 'CLI', cd2: 'Angular', cd9: 'false' }
}
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Options',
  label: '{"log":"trace","$0":"tns","bundle":"webpack","profileDir":"private"}',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Will send the following information to Google Analytics: {
  type: 'PreviewAppData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Preview App Data',
  platform: 'iOS',
  label: 'iOS',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' }
}
Searching for devices...
startLookingForDevices; platform is iOS
Options for ios-device-discovery {
  platform: 'iOS',
  shouldReturnImmediateResult: false,
  emulator: false,
  fullDiscovery: undefined
}
iTunes is not installed. Install it on your system and run this command again.
Found device with identifier 'C9F25B26-0203-4179-A0E2-5D2DFB436504'
startLookingForDevices; platform is iOS
Options for ios-device-discovery {
  platform: 'iOS',
  shouldReturnImmediateResult: false,
  emulator: false,
  fullDiscovery: undefined
}
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Using Runtime Version',
  label: 'ios__6.5.0',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command prepare is before-prepare
Creating NativeScript project for the ios platform
Path: /Users/arijitdas/Autility/Repository/test/platforms/ios
Package: org.nativescript.test
Name: test
Copying template files...
⠋ Calling pacoteService.extractPackage for packageName: 'tns-ios@6.5.0', destinationDir: '/var/folders/53/v1r07dj131n5xltc352rn_rm0000gn/T/runtimeDir1201115-2937-114wi1t.bby9' and options: undefined
⠹ Exec npm config get cache 
 stdout: /Users/arijitdas/.npm
 
 stderr: 
Calling pacoteService.extractPackage for packageName: 'tns-ios@6.5.0', destinationDir: '/var/folders/53/v1r07dj131n5xltc352rn_rm0000gn/T/runtimeDir1201115-2937-114wi1t.bby9' and options: undefined
Creating extract tar stream with options: {
  "strip": 1,
  "C": "/var/folders/53/v1r07dj131n5xltc352rn_rm0000gn/T/runtimeDir1201115-2937-114wi1t.bby9"
}
⠸ Successfully extracted 'tns-ios@6.5.0' to /var/folders/53/v1r07dj131n5xltc352rn_rm0000gn/T/runtimeDir1201115-2937-114wi1t.bby9
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Add Platform',
  label: 'ios__6.5.0',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Found shared scheme at xcschemeFilePath, renaming to match project name.
Checkpoint 0
Checkpoint 1
Checkpoint 2
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'AddPlatformService__addNativePlatform',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 101
}
Platform ios successfully added. v6.5.0
Preparing project...
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command watch is before-watch
spawn: /usr/local/bin/node "--max_old_space_size=4096" "--preserve-symlinks" "/Users/arijitdas/Autility/Repository/test/node_modules/webpack/bin/webpack.js" "--config=/Users/arijitdas/Autility/Repository/test/webpack.config.js" "--env.hmr" "--env.ios" "--env.appPath=src" "--env.appResourcesPath=App_Resources" "--env.verbose" "--env.sourceMap" "--watch"
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'WebpackCompilerService__startWebpackProcess',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 9
}
clean-webpack-plugin: /Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/**/* has been removed.
Compiling @angular/animations : module as esm5
Compiling @angular/core : module as esm5
Compiling @angular/animations/browser : module as esm5
Compiling @angular/animations/browser/testing : module as esm5
Compiling @angular/common : module as esm5
Compiling @angular/common/http : module as esm5
Compiling @angular/common/http/testing : module as esm5
Compiling @angular/core/testing : module as esm5
Compiling @angular/platform-browser : module as esm5
Compiling @angular/platform-browser-dynamic : module as esm5
Compiling @angular/platform-browser/testing : module as esm5
Compiling @angular/compiler/testing : module as esm5
Compiling @angular/platform-browser-dynamic/testing : module as esm5
Compiling @angular/common/testing : module as esm5
Compiling @angular/router : module as esm5
Compiling @angular/router/testing : module as esm5
Compiling @angular/platform-browser/animations : module as esm5
Compiling @angular/forms : module as esm5
File change detected. Starting incremental webpack compilation...
Message from webpack File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: e32cfedb1dcde2218e10
Version: webpack 4.27.1
Time: 8621ms
Built at: 12/15/2020 4:16:30 PM
                                            Asset       Size                                          Chunks             Chunk Names
                                        bundle.js   40.2 KiB                                          bundle  [emitted]  bundle
                                     package.json  112 bytes                                                  [emitted]  
                                       runtime.js   71.4 KiB                                         runtime  [emitted]  runtime
tns_modules/tns-core-modules/inspector_modules.js  666 bytes  tns_modules/tns-core-modules/inspector_modules  [emitted]  tns_modules/tns-core-modules/inspector_modules
                                        vendor.js     18 MiB                                          vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/tns-core-modules/inspector_modules = runtime.js vendor.js tns_modules/tns-core-modules/inspector_modules.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[./app.css] 2.01 KiB {bundle} [built]
[./app/app-routing.module.ts] 778 bytes {bundle} [built]
[./app/app.component.html] 167 bytes {bundle} [built]
[./app/app.component.ts] 379 bytes {bundle} [built]
[./app/app.module.ts] 1.49 KiB {bundle} [built]
[./app/item/item-detail.component.html] 365 bytes {bundle} [built]
[./app/item/item-detail.component.ts] 1000 bytes {bundle} [built]
[./app/item/item.service.ts] 1.59 KiB {bundle} [built]
[./app/item/items.component.html] 1.69 KiB {bundle} [built]
[./app/item/items.component.ts] 758 bytes {bundle} [built]
[./main.ts] 2.07 KiB {bundle} [built]
[./package.json] 100 bytes {bundle} {tns_modules/tns-core-modules/inspector_modules} [optional] [built]
    + 607 hidden modules
Webpack compilation complete. Watching for file changes.
Message from webpack Webpack compilation complete.
Webpack build done!
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command watchPatterns is before-watchPatterns
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command watchPatterns is after-watchPatterns
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command prepareNativeApp is before-prepareNativeApp
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command checkForChanges is before-checkForChanges
Executing before-checkForChanges hook at location /Users/arijitdas/Autility/Repository/test/hooks/before-checkForChanges/nativescript-core.js in-process
Validating before-checkForChanges arguments.
Executing before-checkForChanges hook at location /Users/arijitdas/Autility/Repository/test/hooks/before-checkForChanges/nativescript-dev-webpack.js in-process
Validating before-checkForChanges arguments.
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'before-checkForChanges__nativescript-core.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 10
}
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'before-checkForChanges__nativescript-dev-webpack.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 8
}
Set configChanged to true, appResourcesChanged is: true
checkForChanges returns ProjectChangesInfo {
  appResourcesChanged: true,
  configChanged: true,
  nativeChanged: true,
  nsConfigChanged: true,
  nativePlatformStatus: '2'
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command checkForChanges is after-checkForChanges
Images from Xcode project
[]
Current images from App_Resources
[ 'Assets.xcassets', 'LaunchScreen.storyboard', 'build.xcconfig' ]
New images to add into xcode project: Assets.xcassets, LaunchScreen.storyboard, build.xcconfig
Images to remove from xcode project: 
Successfully prepared plugin @nativescript/angular for ios.
Successfully prepared plugin @nativescript/theme for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin nativescript-intl for ios.
Message from webpack {
  emittedFiles: [
    'bundle.js',
    'runtime.js',
    'tns_modules/tns-core-modules/inspector_modules.js',
    'vendor.js',
    'package.json'
  ],
  chunkFiles: [
    'bundle.js',
    'runtime.js',
    'tns_modules/tns-core-modules/inspector_modules.js',
    'vendor.js'
  ],
  hash: 'e32cfedb1dcde2218e10'
}
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/Podfile is 32c7118af05cda2870d9693d93b4c9376840221e
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/native-api-usage.json is 57877386fe966e8697d5c5dbc50d42feab6bed8c
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/src/NativeScriptEmbedder.h is 61d5332c711cc0ac62e0194e18077d2ff5293b11
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/src/NativeScriptEmbedder.m is 177d5673fac79dff28d09182eaef20778f66e787
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/src/module.modulemap is e3696280d924e540c4525889e025e1314ec183b9
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/typings/objc!MaterialComponents.d.ts is 7ed17f247f445c1ae064ae00d1b9024c9c2650a1
Successfully prepared plugin @nativescript/core for ios.
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSProcess.h is 787f09c57ede174d6323990e6d6e9eaf134da6f0
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/NSString+Async.h is a3cdfaeb2f7360c395c8e6c2defb4a2b2ffc8f10
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSLabel.h is c7c5788d3ea834d96cf8a137cbf0c4ea28fd7829
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/NSData+Async.h is 4eae4f66d67dc99a53dbbb7c2d8cf1b3df7eb487
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/TNSWidgets.h is 814beee5b8d98390227b9889d64af11660eb1f09
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/UIView+PassThroughParent.h is cddc4157f40983b34fcb1d3846666b5ecc5b1ca5
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers/UIImage+TNSBlocks.h is 3b31a5be818e25c142e99f98479c538632d350ae
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Info.plist is 615a01ba7fa48b8aa53f6c0cf2a5dade94d48475
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Modules/module.modulemap is 00d2220e76eb098f1808eb4e9b5c43ad4cadf1da
Shasum of file /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets is 9ea297ea46be561c2a4110ef765b644ea4a34443
spawn: file "/Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets"
Successfully prepared plugin tns-core-modules-widgets for ios.
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/angular/platforms/ios/Info.plist
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/theme/platforms/ios/Info.plist
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules/platforms/ios/Info.plist
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/nativescript-intl/platforms/ios/Info.plist
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/Info.plist
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/Info.plist
Schedule merge plist at: /Users/arijitdas/Autility/Repository/test/App_Resources/iOS/Info.plist
Info.plist: Start
Info.plist: Patch 'App_Resources/iOS/Info.plist'
Info.plist: Patch 'CFBundleIdentifier from package.json nativescript.id'
Info.plist: Patch 'CFBundleURLTypes from package.json nativescript.id'
Info.plist: Complete
Info.plist: Write to: /Users/arijitdas/Autility/Repository/test/platforms/ios/test/test-Info.plist
File change detected. Starting incremental webpack compilation...
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/angular/platforms/ios/app.entitlements
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/theme/platforms/ios/app.entitlements
No plist found at: /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules/platforms/ios/app.entitlements
Message from webpack File change detected. Starting incremental webpack compilation...
Webpack compilation complete. Watching for file changes.
Message from webpack Webpack compilation complete.
Webpack build done!
Message from webpack {
  emittedFiles: [ 'bundle.js', 'tns_modules/tns-core-modules/inspector_modules.js' ],
  chunkFiles: [
    'bundle.js',
    'runtime.js',
    'tns_modules/tns-core-modules/inspector_modules.js',
    'vendor.js'
  ],
  hash: 'e32cfedb1dcde2218e10'
}
Generated data from webpack message: {
  files: [
    '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/bundle.js',
    '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/tns_modules/tns-core-modules/inspector_modules.js'
  ],
  hasOnlyHotUpdateFiles: false,
  hmrData: {
    hash: '',
    fallbackFiles: [
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/bundle.js',
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/runtime.js',
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/tns_modules/tns-core-modules/inspector_modules.js',
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/vendor.js',
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/bundle.js',
      '/Users/arijitdas/Autility/Repository/test/platforms/ios/test/app/tns_modules/tns-core-modules/inspector_modules.js'
    ]
  },
  platform: 'ios'
}
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-debug.xcconfig'))" 
 stdout:  
 stderr: 
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-release.xcconfig').merge(Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-release.xcconfig'))" 
 stdout:  
 stderr: 
Installing pods...
spawn: pod "install"
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (94.5.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `test.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/Pods/Target Support Files/Pods-test/Pods-test.debug.xcconfig')).save_as(Pathname.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-debug.xcconfig'))" 
 stdout:  
 stderr: 
Exec ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-release.xcconfig').merge(Xcodeproj::Config.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/Pods/Target Support Files/Pods-test/Pods-test.release.xcconfig')).save_as(Pathname.new('/Users/arijitdas/Autility/Repository/test/platforms/ios/plugins-release.xcconfig'))" 
 stdout:  
 stderr: 
There's no application configuration for metadata filtering for platform ios. Full metadata will be generated.
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command prepareNativeApp is after-prepareNativeApp
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'PrepareNativePlatformService__prepareNativePlatform',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 2763
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command checkForChanges is before-checkForChanges
Executing before-checkForChanges hook at location /Users/arijitdas/Autility/Repository/test/hooks/before-checkForChanges/nativescript-core.js in-process
Validating before-checkForChanges arguments.
Executing before-checkForChanges hook at location /Users/arijitdas/Autility/Repository/test/hooks/before-checkForChanges/nativescript-dev-webpack.js in-process
Validating before-checkForChanges arguments.
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command watch is after-watch
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'before-checkForChanges__nativescript-core.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 1
}
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'before-checkForChanges__nativescript-dev-webpack.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 0
}
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/App_Resources/iOS
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/App_Resources/iOS/Assets.xcassets
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/App_Resources/iOS/Assets.xcassets/LaunchScreen.AspectFill.imageset
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/App_Resources/iOS/Assets.xcassets/LaunchScreen.Center.imageset
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/src
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/@nativescript/core/platforms/ios/typings
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Headers
containsNewerFiles will check /Users/arijitdas/Autility/Repository/test/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/Modules
Set nativeChanged to false.
Set value of configChanged to false
checkForChanges returns ProjectChangesInfo {
  appResourcesChanged: false,
  nativeChanged: false,
  nsConfigChanged: false,
  configChanged: false,
  nativePlatformStatus: '3'
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command checkForChanges is after-checkForChanges
Project successfully prepared (ios)
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command prepare is after-prepare
Executing after-prepare hook at location /Users/arijitdas/Autility/Repository/test/hooks/after-prepare/nativescript-dev-webpack.js in-process
Validating after-prepare arguments.
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'after-prepare__nativescript-dev-webpack.js',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 95
}
Building project...
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Performance',
  label: 'PrepareController__prepareCore',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: 23303
}
Will send the following information to Google Analytics: {
  type: 'googleAnalyticsData',
  category: 'CLI',
  googleAnalyticsDataType: 'event',
  action: 'Build',
  label: 'iOS_Simulator_Debug_Incremental',
  customDimensions: { cd2: 'Angular', cd9: 'false', cd5: 'CLI' },
  value: undefined
}
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
BeforeHookName for command buildIOS is before-buildIOS
Xcode build...
spawn: xcodebuild "ONLY_ACTIVE_ARCH=NO" "CODE_SIGN_IDENTITY=" "build" "-configuration" "Debug" "-sdk" "iphonesimulator" "BUILD_DIR=/Users/arijitdas/Autility/Repository/test/platforms/ios/build" "SHARED_PRECOMPS_DIR=/Users/arijitdas/Autility/Repository/test/platforms/ios/build/sharedpch" "-workspace" "/Users/arijitdas/Autility/Repository/test/platforms/ios/test.xcworkspace" "-scheme" "test"
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY= build -configuration Debug -sdk iphonesimulator BUILD_DIR=/Users/arijitdas/Autility/Repository/test/platforms/ios/build SHARED_PRECOMPS_DIR=/Users/arijitdas/Autility/Repository/test/platforms/ios/build/sharedpch -workspace /Users/arijitdas/Autility/Repository/test/platforms/ios/test.xcworkspace -scheme test

Build settings from command line:
    BUILD_DIR = /Users/arijitdas/Autility/Repository/test/platforms/ios/build
    CODE_SIGN_IDENTITY = 
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator14.3
    SHARED_PRECOMPS_DIR = /Users/arijitdas/Autility/Repository/test/platforms/ios/build/sharedpch

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'MDFInternationalization' from project 'Pods')
error: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')

** BUILD FAILED **

Command xcodebuild failed with exit code 65
Unable to apply changes on device: C9F25B26-0203-4179-A0E2-5D2DFB436504. Error is: Command xcodebuild failed with exit code 65.
Will emit event runOnDeviceError with data {
  projectDir: '/Users/arijitdas/Autility/Repository/test',
  deviceIdentifier: 'C9F25B26-0203-4179-A0E2-5D2DFB436504',
  applicationIdentifier: 'org.nativescript.test',
  error: Error: Command xcodebuild failed with exit code 65
      at Errors.failWithOptions (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:147:28)
      at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:21)
      at XcodebuildCommandService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:28:30)
      at Generator.throw (<anonymous>)
      at rejected (/usr/local/lib/node_modules/nativescript/lib/services/ios/xcodebuild-command-service.js:5:65)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    name: 'Exception',
    errorCode: 127,
    suggestCommandHelp: false,
    proxyAuthenticationRequired: false,
    printOnStdout: undefined
  }
}
Stopping webpack watch for platform ios.
Project dir from hooksArgs is: /Users/arijitdas/Autility/Repository/test.
Hooks directories: [ '/Users/arijitdas/Autility/Repository/test/hooks' ]
AfterHookName for command watch is after-watch
Will emit event runOnDeviceStopped with data {
  projectDir: '/Users/arijitdas/Autility/Repository/test',
  deviceIdentifier: 'C9F25B26-0203-4179-A0E2-5D2DFB436504'
}
Webpack process exited with code null when we expected it to be long living with watch.

**Comment by dasarijit88** [comment]
If i run from xcode , i get the below error
```
~/Autility/Repository/test/platforms/ios
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/arijitdas/Autility/Repository/test/platforms/ios/internal//NativeScript.framework/NativeScript' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by JohanBeumer** [comment]
I get the same error when I do :

- ns create foo --ng
- cd foo
- ns debug ios

✔ Component nativescript has 7.0.11 version and is up to date.
✔ Component @nativescript/core has 7.0.13 version and is up to date.
✔ Component @nativescript/ios has 7.0.6 version and is up to date.

This started happening after updating my mac to Big sur 11.1 and xcode 12.3 12C33

**Comment by boris01** [comment]
I get this error also,
After Xcode updated to the 12.3 (12C33) on Catalina.
✔ Component nativescript cli has 7.0.11 version and is up to date.
✔ Component @nativescript/core has 7.0.13 version and is up to date.
✔ Component @nativescript/ios has 7.0.6 version and is up to date.

Building project...
Xcode build...
note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override:
note: Planning build
note: Constructing build description
error: Building for iOS Simulator, but the linked and embedded framework 'TNSCore.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')
error: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')
error: Building for iOS Simulator, but the linked and embedded framework 'TNSChart.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')
** BUILD FAILED **
Unable to apply changes on device: 554E73F9-1310-40B8-A259-840D2220FF7C. Error is: Command xcodebuild failed with exit code 65.

**Comment by michaelsmedley** [comment]
Just started to occur for me this morning.

All I can think is that I updated to Big Sur 11.1 last night and Xcode seems to have potentially updated as a result of it

**Comment by michaelsmedley** [comment]
Seems to be affecting other people over the last 24 hours actually.

There's a thread with possible solutions at https://stackoverflow.com/questions/65303304/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa

**Comment by dasarijit88** [comment]
@michaelsmedley - I went through the above link for possible solution but I don't see the option Validate Workspace for the target and yes it started occurring after the latest update.
![Screenshot 2020-12-16 at 09 37 05](https://user-images.githubusercontent.com/62553135/102324727-84213800-3f82-11eb-9ee3-d53f83cf1a40.png)

**Comment by michaelsmedley** [comment]
@dasarijit88 If you start searching for "Validate" then the option should appear

<img width="722" alt="image" src="https://user-images.githubusercontent.com/2039847/102325041-9303ec80-3f7a-11eb-9c3a-a1465eea615d.png">

**Comment by dasarijit88** [comment]
@michaelsmedley - thanks , but the issue still persists. After I added arm64 in the excluded architecture, the error changes into warnings but the application does not start.

Xcode build...
In file included from /Users/arijitdas/Autility/Repository/test/platforms/ios/internal/main.m:5:
In file included from /Users/arijitdas/Autility/Repository/test/platforms/ios/internal/TNSExceptionHandler.h:13:
In file included from /Users/arijitdas/Autility/Repository/test/platforms/ios/internal/NativeScript.framework/Headers/NativeScript.h:12:
/Users/arijitdas/Autility/Repository/test/platforms/ios/internal/NativeScript.framework/Headers/TNSRuntimeInstrumentation.h:15:48: warning: 
      this block declaration is not a prototype [-Wstrict-prototypes]
+ (id)profile:(NSString*)name withBlock:(id (^)())block;
                                               ^
                                                void
/Users/arijitdas/Autility/Repository/test/platforms/ios/internal/NativeScript.framework/Headers/TNSRuntimeInstrumentation.h:16:27: warning: 
      this block declaration is not a prototype [-Wstrict-prototypes]
+ (id)profileBlock:(id (^)())block withName:(NSString* (^)())nameBlock;
                          ^
                           void
/Users/arijitdas/Autility/Repository/test/platforms/ios/internal/NativeScript.framework/Headers/TNSRuntimeInstrumentation.h:16:59: warning: 
      this block declaration is not a prototype [-Wstrict-prototypes]
+ (id)profileBlock:(id (^)())block withName:(NSString* (^)())nameBlock;
                                                          ^
                                                           void
In file included from /Users/arijitdas/Autility/Repository/test/platforms/ios/internal/main.m:11:
/Users/arijitdas/Autility/Repository/test/platforms/ios/internal/TNSDebugging.h:126:48: warning: 
      this block declaration is not a prototype [-Wstrict-prototypes]
      __block void (^decrementDispatchOpsCount)() = ^{
                                               ^
                                                void
In file included from /Users/arijitdas/Autility/Repository/test/platforms/ios/internal/main.m:12:
/Users/arijitdas/Autility/Repository/test/platforms/ios/internal/TKLiveSync/include/TKLiveSync.h:17:27: warning: 
      this function declaration is not a prototype [-Wstrict-prototypes]
void TNSInitializeLiveSync();
                          ^
                           void
5 warnings generated.
note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'test' from project 'test')
Project successfully built.
The build result is located at: /Users/arijitdas/Autility/Repository/test/platforms/ios/build/Debug-iphonesimulator/test.app
Installing on device 72C953E8-3374-4956-9937-F00DC2B912CF...
Successfully installed on device with identifier '72C953E8-3374-4956-9937-F00DC2B912CF'.
Successfully transferred bundle.js on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred package.json on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred runtime.js on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred tns_modules on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred tns-core-modules on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred inspector_modules.js on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Successfully transferred vendor.js on device 72C953E8-3374-4956-9937-F00DC2B912CF.
Restarting application on device 72C953E8-3374-4956-9937-F00DC2B912CF...

**Comment by michaelsmedley** [comment]
Weird - I'm afraid the inner workings of Nativescript -> iOS are a bit beyond me so I don't think I'll be able to provide any more help here, especially when it tells you that it builds!

There was a suggestion I saw about using the legacy build system (File -> Workspace Settings -> Build System) - maybe it's worth just giving that a shot?

**Comment by boris01** [comment]
According to Apple here: https://developer.apple.com/forums/thread/669411?answerId=652663022#652663022

> This framework isn't built with a supported configuration -- iOS and iOS Simulator code has never been supported in the same binary. The linker in Xcode 11 began identifying these incorrect configurations and issuing warnings, and Xcode 12 goes further in identifying these issues.
> 
> The only correct way to resolve this is to rebuild the framework as an XCFramework. If this is your framework, or owned by another group in your company, follow the information in the video and the Xcode Help article.
> 
> If this framework is from a vendor, then you need to work with the vendor to get an updated version of the framework built with supported configuration.
> 
> In the discussion of this thread, there is a build script that attempts to resolve this error. Scripts like that -- anything that tries to manipulate the output with commands like lipo -- still produces an unsupported configuration in the binary. XCFrameworks are the way to go

So, the only way to properly fix it, is to recompile the TNSCore.framework, TNSWidgets.framework and TNSChart.framework to the XCFrameworks.

**Comment by dasarijit88** [comment]
Now after I enabled **Validate Workspace** to **Yes** and add **arm64**  to **Excluded Architecture** . the error vanishes and the application launches with flash screen and crashes immediately, when I tried running from Xcode , I get the below error.
![Screenshot 2020-12-16 at 11 36 53](https://user-images.githubusercontent.com/62553135/102337996-8213a500-3f93-11eb-8a34-ed5f7b001fe4.png)

**Comment by AlbanRicherPro** [comment]
Adding 
```
...
VALIDATE_WORKSPACE = YES;
```
in the `app/App_Resources/iOS/build.xcconfig` file fixed the issue for me.

This is the shortcut to enable the option `Validate Workspace` in XCode.

I didn't change anything else and it totally solved the problem.

**Comment by dasarijit88** [comment]
@AlbanRicherPro - I did the same thing but that only suppress the error as warning , however the application crashes

**Comment by AlbanRicherPro** [comment]
I don't have crashes in the application.

Did you try without adding `arm64` in the excluded architecture?

**Comment by dasarijit88** [comment]
@AlbanRicherPro - Yes i tried without arm64 but then i was getting the error  **ld: building for iOS Simulator, but linking in dylib built for iOS, file.** I have now downgraded to Xcode 12.2 and everything looks fine. Hope we will get a generic solution for Xcode 12.3 soon

**Comment by AlbanRicherPro** [comment]
@dasarijit88 Sorry for not helping you 😕

**Comment by calc001** [comment]
@AlbanRicherPro this did the job for me. thanks

**Comment by phillip389** [comment]
> Adding
> 
> ```
> ...
> VALIDATE_WORKSPACE = YES;
> ```
> 
> in the `app/App_Resources/iOS/build.xcconfig` file fixed the issue for me.
> 
> This is the shortcut to enable the option `Validate Workspace` in XCode.
> 
> I didn't change anything else and it totally solved the problem.

Worked for me. Thanks

**Comment by ihazar** [comment]
Adding arm64 in the excluded architecture, and
And adding `VALIDATE_WORKSPACE = YES;` in the app/App_Resources/iOS/build.xcconfig
Worked for me, but I had to run ios withour HMR using `tns run ios --no-hmr`

**Comment by matteonatale** [comment]
> Adding
> 
> ```
> ...
> VALIDATE_WORKSPACE = YES;
> ```
> 
> in the `app/App_Resources/iOS/build.xcconfig` file fixed the issue for me.
> 
> This is the shortcut to enable the option `Validate Workspace` in XCode.
> 
> I didn't change anything else and it totally solved the problem.

This solved the issue also for me. Thanks! :D

**Comment by ejlocop** [comment]
adding didn't work for me. any workaround to fix this one?
```
VALIDATE_WORKSPACE = YES;
```

**Comment by matteonatale** [comment]
The first time that i added this line didn't work for me either, than i noticed that my build.xcconfig file had a `.default` extension and looked like`build.xcconfig.default`. I removed the `.default` extension, and it worked.

**Comment by enstenr** [comment]
Hi,
I am stuck at the exact issue. 
I have a live project and few days back when I upgraded to BigSur and Xcode to 12.3 with NativeScript 6.5.0  , 
tns run iOS --bundle command fails with below warning & ERROR

**_warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'MDFInternationalization' from project 'Pods')
error: Building for iOS Simulator, but the linked and embedded framework 'TNSWidgets.framework' was built for iOS + iOS Simulator. (in target 'projectname' from project 'projectname')
** BUILD FAILED **_**


Any help would be appreciated. 
Am totally stuck here past one week. I have been searching through all resources and options, nothing really solving it for me. 

Command xcodebuild failed with exit code 65

If I downgrade my Mac , will that solve , any help would be highly appreciated

**Comment by JimLynchCodes** [comment]
`VALIDATE_WORKSPACE = YES;` is not working for me... 😢

**Comment by ihazar** [comment]
> `VALIDATE_WORKSPACE = YES;` is not working for me... 😢

Try running without Hot Module Replacement by `tns run ios --no-hmr`

**Comment by mehmetfarhan** [comment]
In my case, I solved this problem by simply setting **_Validate Workspace_** to **Yes** in the Build Settings tab.

**Comment by limyandi** [comment]
Hey guys, just wondering what does 'Validate Workspace' actually do?

**Comment by nileshv123** [comment]
@AlbanRicherPro, I tried to downgrade in Xcode 12.2 using downloading the Xcode_12.2.xip file and when clicking to the .xip file but facing the issue "The archive ' Xcode_12.2.xip' is damaged and can't be expanded".

Could you provide me how to downgrade in Xcode 12.2?

**Comment by AlbanRicherPro** [comment]
> @AlbanRicherPro, I tried to downgrade in Xcode 12.2 using downloading the Xcode_12.2.xip file and when clicking to the .xip file but facing the issue "The archive ' Xcode_12.2.xip' is damaged and can't be expanded".
> 
> Could you provide me steps on how to downgrade in Xcode 12.2?

I'am using Xcode 12.3, but sorry I don't know how to downgrade to Xcode 12 😕 

There is a new version of the [`tns-ios`](https://www.npmjs.com/package/tns-ios) dependency and it should also resolve the problem.

**Comment by nileshv123** [comment]
> @AlbanRicherPro, I tried to downgrade in Xcode 12.2 using downloading the Xcode_12.2.xip file and when clicking to the .xip file but facing the issue "The archive ' Xcode_12.2.xip' is damaged and can't be expanded".
> 
> Could you provide me steps on how to downgrade in Xcode 12.2?

@dasarijit88. my comment was for you accidentally tagged.

**Comment by nileshv123** [comment]
@AlbanRicherPro, I'm also using Xcode 12.3 and tns-ios version 4.1.1 but unable to resolve the problem.

which tns-ios version you are using?

**Comment by rigor789** [comment]
@nileshv123 4.1.1 is very old, try `6.5.4`.

**Comment by AlbanRicherPro** [comment]
@nileshv123 I'm using `6.5.4`

**Comment by kennethkeim** [comment]
> So, the only way to properly fix it, is to recompile the TNSCore.framework, TNSWidgets.framework and TNSChart.framework to the XCFrameworks.

Isn't @boris01 correct here that the framework needs to be recompiled? Any plans for that in future releases?

**Comment by NathanWalker** [comment]
tns-ios 6.5.4
@nativescript/ios 7.1.0

Either one is what you at least want to be using. Stated here:
https://nativescript.org/blog/nativescript-7-1-hmr-reenabled-and-xcode-12-3-support/

**Comment by exeptionerror** [comment]
Here Is Already Solved with all possible solution added [Solved Xcode 12.3: Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator](https://exerror.com/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa/)

**Comment by luisVargasGu** [comment]
None of these are working for me, much like @dasarijit88 . Could it be a problem with the new M1 mac-books?

**Comment by davorpeic** [comment]
This issue still persist in NS8 and happens with default "template-drawer-navigation-ng" template trying to build on M1 mbpro and run in simulator. I hope someone provide a working solution.
Xcode Version 12.5

**Comment by Reached** [comment]
Any updates on this team? Struggling with the same thing :/

**Comment by DerZyklop** [comment]
Still happening. 
M1 MacBook Pro 2021
macOS Monterey 12.2
Xcode version 13.2.1
Nativescript version 8.1.5

**Comment by rigor789** [comment]
@DerZyklop share the output from running:
```bash
echo 'y' | npx nativescript-envinfo
```

And the build logs with the error - it could be related to an outdated plugin not shipping arm64 slices in their native lib.

**Comment by DerZyklop** [comment]
Found out that it is not working on my M1, when I set `VALIDATE_WORKSPACE = YES` like [AlbanRicherPro did](https://github.com/NativeScript/nativescript-cli/issues/5449#issuecomment-746365706). 
But worked for me when I [set it manually](https://github.com/NativeScript/nativescript-cli/issues/5449#issuecomment-745924785).

Not sure if this makes sense.

@rigor789 in case you are still interested…
```sh
$ echo 'y' | npx nativescript-envinfo
```
⬇ 
```yaml
OS: macOS 12.2
CPU: (10) x64 Apple M1 Pro
Shell: /bin/bash
node: 16.13.2
npm: 8.1.2
nativescript: 8.1.5

# android
java: 11.0.11
ndk: Not Found
apis: 25, 28
build_tools: 25.0.2, 29.0.3
system_images: 
  - android-26 | Google APIs Intel x86 Atom_64
  - android-28 | Google APIs ARM 64 v8a
  - android-29 | Google APIs ARM 64 v8a
  - android-30 | Google APIs ARM 64 v8a

# ios
xcode: 13.2.1/13C100
cocoapods: 1.11.2
python: 2.7.18
python3: 3.9.10
ruby: 2.6.8
platforms: 
  - DriverKit 21.2
  - iOS 15.2
  - macOS 12.1
  - tvOS 15.2
  - watchOS 8.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "7.0.3",
  "@nativescript/firebase": "11.0.0",
  "@nativescript/local-notifications": "5.0.0",
  "@nativescript/theme": "2.5.0",
  "nativescript-dna-deviceinfo": "2.4.3",
  "@nativescript/localize": "5.0.2",
  "nativescript-webview-interface2": "1.4.7",
  "nativescript-webview-utils": "3.0.1"
},
"devDependencies": {
  "@nativescript/android": "7.0.0",
  "@nativescript/ios": "7.0.0",
  "@nativescript/types": "7.0.3",
  "@nativescript/webpack": "3.0.4",
  "nativescript-remote-builds": "1.1.1",
  "typescript": "3.9.7"
}
```
