### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by benwainaina** [NativeScript/nativescript-cli#5509]
**Environment**
 - CLI: 8.0.0

The rest of the environment checks do not apply since I am trying to create a project.

**Describe the bug**
So, I recently updated my nativescript to version 8.0.0. When I make an attempt to run:

`ns create appName --template @nativescript/template-blank-ng`

I get the below warning:

**You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.**

then I get this error:

The "path" argument must be of type string. Received null

And so I cannot be able to create a new project

**To Reproduce**

1.Upgrade to version 8.0.0 using `npm i -g nativescript` (I actually wen further and uninstalled the existing version and re-installed again)
2. Run `ns create appName --template @nativescript/template-blank-ng`

**Expected behavior**

It should create a nativescript application with a blank Angular template

**Additional context**
Ubuntu 20.04 LTS
Node 14.15.3

**Comment by 4f3x** [comment]
This output is produced:

```
ns create ns-drawer --template @nativescript/template-drawer-navigation-vue --log trace --path /Users/fex/Code/HN/ns-drawer

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*                                                                                                                                               *
*  The "TRACE" log level might print some sensitive data like secrets or access tokens in request URLs. Be careful when you share this output.  *
*                                                                                                                                               *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *


Trying to get macOS version.
Exec system_profiler SPSoftwareDataType -detailLevel mini
 stdout: Software:

    System Software Overview:

      System Version: macOS 11.2.3 (20D91)
      Kernel Version: Darwin 20.3.0
      Time since boot: 1:25


 stderr:
macOS version based on system_profiler is 11.2.
Looking for project in '/Users/fex/Code/HN/ns-drawer'
Looking for project in '/Users/fex/Code/HN'
Looking for project in '/Users/fex/Code'
Looking for project in '/Users/fex'
Looking for project in '/Users'
Looking for project in '/'
No project found at or above '/Users/fex/Code/HN/ns-drawer'.
Unable to find project. projectDir: null, options.path: /Users/fex/Code/HN/ns-drawer, /Users/fex/Code/HN/ns-drawer
No project found at or above '%s' and neither was a --path specified.
Loading extensions.
Unable to find project. projectDir: null, options.path: /Users/fex/Code/HN/ns-drawer, /Users/fex/Code/HN/ns-drawer
No project found at or above '%s' and neither was a --path specified.
...
```

The resulting error message:

```
...
You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
failed to add embedded package.json data to config TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.resolve (path.js:980:7)
    at ProjectData.getAppDirectoryRelativePath (/usr/local/lib/node_modules/nativescript/lib/project-data.js:133:34)
    at ProjectConfigService.fallbackToLegacyNSConfig (/usr/local/lib/node_modules/nativescript/lib/services/project-config-service.js:202:101)
    at ProjectConfigService.readConfig (/usr/local/lib/node_modules/nativescript/lib/services/project-config-service.js:104:25)
    at ProjectData.initializeProjectDataFromContent (/usr/local/lib/node_modules/nativescript/lib/project-data.js:61:45)
    at ProjectData.initializeProjectData (/usr/local/lib/node_modules/nativescript/lib/project-data.js:50:22)
    at ProjectDataService.getProjectData (/usr/local/lib/node_modules/nativescript/lib/services/project-data-service.js:76:43)
    at ProjectService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/project-service.js:149:70)
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at ProjectConfigService.fallbackToLegacyNSConfig (/usr/local/lib/node_modules/nativescript/lib/services/project-config-service.js:216:52)
    at ProjectConfigService.readConfig (/usr/local/lib/node_modules/nativescript/lib/services/project-config-service.js:104:25)
    at ProjectData.initializeProjectDataFromContent (/usr/local/lib/node_modules/nativescript/lib/project-data.js:61:45)
    at ProjectData.initializeProjectData (/usr/local/lib/node_modules/nativescript/lib/project-data.js:50:22)
    at ProjectDataService.getProjectData (/usr/local/lib/node_modules/nativescript/lib/services/project-data-service.js:76:43)
    at ProjectService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/project-service.js:149:70)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/project-service.js:11:58)
```

**Comment by rigor789** [comment]
Thanks for the report, it turns out to be a bad template publish on our part, I just bumped out a new release of all the broken templates, and the command should be working properly now!

**Comment by 4f3x** [comment]
Unfortunately the error still occurs for me when referring the npm repository. Might this be a caching issue on my side?
