### ISSUE TITLE
Can't build any plugins (Android) *Failed to build plugin @nativesctript/core

### ISSUE THREAD

**Issue by CTOaramos** [NativeScript/nativescript-cli#5649]
### Issue Description

Hi, does anyone experienced this ? im trying to run the Hello World Template (Pure Typescript)
![Screen Shot 2022-03-13 at 9 46 56 AM](https://user-images.githubusercontent.com/88295221/158041303-d05a712c-9c3f-401c-91e0-f6d7f1383123.png)

Here's my current versions
![Screen Shot 2022-03-13 at 9 48 08 AM](https://user-images.githubusercontent.com/88295221/158041313-02f8de8a-e715-4457-b204-5c6b72c04860.png)

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
@CTOaramos looks like potentially sdk version related - when possible could you run this command and post the results:

echo 'y' | npx nativescript-envinfo

**Comment by CTOaramos** [comment]
Hi, @NathanWalker thank you for the response here it is;
![Screen Shot 2022-03-13 at 3 36 55 PM](https://user-images.githubusercontent.com/88295221/158050128-e14b0027-a1f2-4e92-b479-6f495150a75e.png)

**Comment by CTOaramos** [comment]
Hi, @NathanWalker, I have added sdkmanager in the $PATH and the it changed;
![Screen Shot 2022-03-13 at 4 15 13 PM](https://user-images.githubusercontent.com/88295221/158051105-069e1c65-3e00-4203-8e14-28f5daa74629.png)


but im still getting the error
![Screen Shot 2022-03-13 at 4 15 21 PM](https://user-images.githubusercontent.com/88295221/158051124-9b65a55b-132c-4e0c-b573-c6c7a74fcffb.png)

**Comment by CTOaramos** [comment]
I downloaded obsolete version of ndk; nativescript-envinfo #android now have all value; but im still getting 
![Screen Shot 2022-03-13 at 5 30 27 PM](https://user-images.githubusercontent.com/88295221/158053427-403ad5d1-5fa8-4ddb-a650-717f2023df7f.png)
![Screen Shot 2022-03-13 at 5 29 45 PM](https://user-images.githubusercontent.com/88295221/158053428-3b45bd34-8fc5-4184-beb9-7eeca0592d85.png)
![Screen Shot 2022-03-13 at 5 29 41 PM](https://user-images.githubusercontent.com/88295221/158053431-0d799c87-69bd-41ea-8aa3-a5a03365ddc3.png)
![Screen Shot 2022-03-13 at 5 29 02 PM](https://user-images.githubusercontent.com/88295221/158053434-f79f64cc-ba6c-4413-8895-25c31f212629.png)
![Screen Shot 2022-03-13 at 5 30 43 PM](https://user-images.githubusercontent.com/88295221/158053425-7d287445-f426-4dac-86d5-ec899e3a2d5b.png)
![Screen Shot 2022-03-13 at 5 30 37 PM](https://user-images.githubusercontent.com/88295221/158053426-4fd1b536-6f5e-4dad-98d5-0abb767276d1.png)
![Screen Shot 2022-03-13 at 5 30 54 PM](https://user-images.githubusercontent.com/88295221/158053423-eb652563-07e3-4585-8205-bec47f298443.png)

This is app is the Hello World template;
![Screen Shot 2022-03-13 at 5 32 32 PM](https://user-images.githubusercontent.com/88295221/158053463-c01e823c-b237-452f-bcf8-b5db7b59477f.png)

**Comment by rigor789** [comment]
@CTOaramos please share your `package.json` - we can try reproducing with your dependencies...

But before any of that, please make sure you install the latest cli - seems like you are on 8.1.5.
There were some fixed in 8.2.x cli that would affect the plugin builds.

`npm i -g nativescript`

**Comment by CTOaramos** [comment]
Hi, @rigor789 Im running the Hello World template Typescript; 

i updated to 8.2.2 still getting error
![Screen Shot 2022-03-15 at 7 52 12 AM](https://user-images.githubusercontent.com/88295221/158279421-25c7a3b0-23eb-432c-8393-d91669696389.png)
![Screen Shot 2022-03-15 at 7 52 24 AM](https://user-images.githubusercontent.com/88295221/158279436-ed011dc7-9d55-4575-a188-ab6bdae029fc.png)
;

**Comment by milosmatic** [comment]
I can confirm that I'm getting the same issue on both newly created projects and existing ones. 

- node v17.7.1
- npm v8.5.2
- ns v8.2.2

**Comment by rigor789** [comment]
Please post the stack-trace, so we can do some searching as well - seems to happen for a few people, but not everyone - there must be some correlation between the cases, we just don't know what yet... 

Since gradle itself is throwing the error, I believe it to be a gradle bug/issue - that's what I would focus my search on...

**Comment by milosmatic** [comment]
![image](https://user-images.githubusercontent.com/1607249/158416177-c6c5c0bd-43a3-407c-8036-4261bc80386f.png)


![image](https://user-images.githubusercontent.com/1607249/158416126-24c1a8d4-584f-4c9c-b753-c2012646ffdd.png)

**Comment by rigor789** [comment]
Please include it in a textual form - I can't copy it from screenshots.

**Comment by milosmatic** [comment]
> ns build android
Copying template files...
⠼ (##################) ⠏ reify:@nativescript/android: http fetch GET 200 https://registry.npmjs.org/@nativescript/android/-/android-8.2.2.Platform android successfully added. v8.2.2
Preparing project...
asset vendor.js 15.4 MiB [emitted] (name: vendor) (id hint: defaultVendor)
asset bundle.js 353 KiB [emitted] (name: bundle)
asset runtime.js 12.5 KiB [emitted] (name: runtime)
Entrypoint bundle 15.8 MiB = runtime.js 12.5 KiB vendor.js 15.4 MiB bundle.js 353 KiB
runtime modules 2.72 KiB 8 modules
orphan modules 576 bytes [orphan] 7 modules
modules by path ./node_modules/ 5.2 MiB
  javascript modules 4.94 MiB 560 modules
  json modules 273 KiB
    modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
    modules by path ./node_modules/css-tree/ 30.7 KiB 2 modules
modules by path ./src/ 125 KiB
  modules by path ./src/app/ 6.62 KiB 6 modules
  modules by path ./src/*.ts 840 bytes
    ./src/polyfills.ts 545 bytes [built] [code generated]
    ./src/main.ts 295 bytes [built] [code generated]
  ./src/app.css 118 KiB [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]
webpack 5.67.0 compiled successfully in 6132 ms
Webpack compilation complete.
Failed to build plugin @nativescript/core :
Error: spawn ./gradlew ENOENT

> Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Input/output error
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
        ... 1 more
         ~ applying user-defined configuration from /Users/milos/Projects/ns-test/App_Resources/Android/before-plugins.gradle

**Comment by milosmatic** [comment]
Here is the trace log [https://pastebin.com/7zGtYWBF](https://pastebin.com/7zGtYWBF)

**Comment by CTOaramos** [comment]
Here's mine; https://pastebin.com/CU6jmN0m

**Comment by milosmatic** [comment]
@rigor789 here is the log after changes https://pastebin.com/KwCLYVRw

**Comment by NathanWalker** [comment]
@milosmatic when you get a chance could you run the following command and copy/paste the results (not screenshots) including the invocation of the command visible in the output:

```
echo 'y' | npx nativescript-envinfo
```

**Comment by milosmatic** [comment]
@NathanWalker here it is

```yaml
OS: macOS 12.3
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 17.7.2
npm: 8.5.2
nativescript: 8.2.2

# android
java: 11.0.14.1
ndk: Not Found
apis: 27, 28, 29, 30, 31
build_tools: 27.0.3, 28.0.3, 29.0.3, 30.0.3, 31.0.0
system_images:
  - android-30 | Google Play ARM 64 v8a

# ios
xcode: 13.3/13E113
cocoapods: 1.11.2
python: 3.9.10
python3: 3.9.10
ruby: 2.7.5
platforms:
  - DriverKit 21.4
  - iOS 15.4
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~13.2.0",
  "@angular/common": "~13.2.0",
  "@angular/compiler": "~13.2.0",
  "@angular/core": "~13.2.0",
  "@angular/forms": "~13.2.0",
  "@angular/platform-browser": "~13.2.0",
  "@angular/platform-browser-dynamic": "~13.2.0",
  "@angular/router": "~13.2.0",
  "@nativescript/angular": "^13.0.0",
  "@nativescript/core": "~8.2.0",
  "@nativescript/theme": "~3.0.2",
  "rxjs": "~7.5.0",
  "zone.js": "~0.11.5"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~13.2.0",
  "@angular/compiler-cli": "~13.2.0",
  "@nativescript/android": "8.2.2",
  "@nativescript/ios": "8.2.1",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "~5.0.6",
  "@ngtools/webpack": "~13.2.0",
  "typescript": "~4.5.5"
}
```

```
ns doctor
✔ Getting environment information

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 13.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.2 version and is up to date.
✔ Component @nativescript/core has 8.2.1 version and is up to date.
✔ Component @nativescript/ios has 8.2.1 version and is up to date.
✔ Component @nativescript/android has 8.2.2 version and is up to date.
```

**Comment by msl2000** [comment]
Having the same gradle issue: Below is my package.json

`{
    "ioas": {
        "v8Flags": "--expose_gc",
        "markingMode": "none",
        "maxLogcatObjectSize": 100900
    },
    "name": "@nativescript/template-blank-vue",
    "main": "app/app.js",
    "displayName": "Blank",
    "version": "8.0.4",
    "description": "NativeScript Application",
    "author": "NativeScript Team <oss@nativescript.org>",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "homepage": "https://github.com/NativeScript/nativescript-app-templates",
    "bugs": {
        "url": "https://github.com/NativeScript/NativeScript/issues"
    },
    "nativescript": {
        "id": "com.dribl.app"
    },
    "publishConfig": {
        "access": "public"
    },
    "files": [
        "app",
        "App_Resources",
        "hooks",
        "tools",
        "!tools/assets",
        ".editorconfig",
        "jsconfig.json"
    ],
    "keywords": [
        "nstudio",
        "nativescript",
        "mobile",
        "{N}",
        "tns",
        "vue",
        "nativescript-vue",
        "template",
        "master-detail",
        "detail",
        "category-general"
    ],
    "dependencies": {
        "@fortawesome/fontawesome-pro": "^5.15.4",
        "@nativescript-community/ui-drawer": "^0.0.33",
        "@nativescript-community/ui-material-bottom-navigation": "^5.3.19",
        "@nativescript-community/ui-material-bottomsheet": "^6.2.5",
        "@nativescript-community/ui-material-tabs": "^5.3.19",
        "@nativescript-community/ui-pulltorefresh": "^2.5.0",
        "@nativescript-community/ui-svg": "0.0.8",
        "@nativescript/background-http": "^5.0.2",
        "@nativescript/camera": "^5.0.10",
        "@nativescript/core": "^8.0.11",
        "@nativescript/datetimepicker": "^2.1.9",
        "@nativescript/firebase": "^11.1.3",
        "@nativescript/imagepicker": "^1.0.6",
        "@nativescript/theme": "~3.0.1",
        "@nstudio/nativescript-pulltorefresh": "^3.0.2",
        "animate.css": "^4.1.1",
        "atob": "^2.1.2",
        "axios": "^0.24.0",
        "buffer": "^6.0.3",
        "file-system": "^2.2.2",
        "fs": "^0.0.1-security",
        "lodash": "^4.17.21",
        "moment": "^2.29.1",
        "nativescript-animate-sass": "^0.0.2",
        "nativescript-appversion": "^1.4.4",
        "nativescript-bottom-navigation": "^2.0.5",
        "nativescript-carousel": "^7.0.1",
        "nativescript-clipboard": "^2.1.1",
        "nativescript-google-maps-sdk": "file:nativescript-google-maps-sdk-4.0.0.tgz",
        "nativescript-vue": "~2.9.0",
        "nativescript-vue-navigator": "^1.2.0",
        "vue-moment": "^4.1.0",
        "vue-slide-up-down": "^2.0.1",
        "vuex": "^3.6.2"
    },
    "devDependencies": {
        "@nativescript/android": "8.0.0",
        "@nativescript/ios": "8.0.0",
        "@nativescript/webpack": "beta",
        "nativescript-vue-template-compiler": "~2.9.0",
        "sass": "^1.42.1"
    },
    "private": "true",
    "readme": "NativeScript Application"
}
`

Using the following: 
Nativescript cli 8.2.2
Java (OpenJDK) 1.8

Same gradle ENOENT error as above

**Comment by CTOaramos** [comment]
Reset my mac the 3rd time; still no luck; this was working 2 months ago; the only things that i did that i think that could cause this are;

- downgraded my node to node@14
- downgraded my jdk from 17 - 1.8

i reset my mac and all use all the updated version; still cannot build any plugin (Hello World Template)

**Comment by NathanWalker** [comment]
@CTOaramos we recommend node 16 or 17 with npm 7 or 8 at least.

**Comment by NathanWalker** [comment]
@milosmatic only thing that jumps out is build-tools 31 which you have installed is corrupted (something on androids side which was discussed couple months back among the android community) - I would recommend installing build-tools 32 and ensure those are set in your app.gradle for example:

compileSdkVersion 32
  buildToolsVersion "32.0.0"
  defaultConfig {  
    minSdkVersion 23
    targetSdkVersion 32

**Comment by milosmatic** [comment]
> 

I'm getting the same error.

```
// You can add your native dependencies here
dependencies {
//  implementation 'androidx.multidex:multidex:2.0.1'
}

compileSdkVersion 32
buildToolsVersion "32.0.0"

android {
  compileSdkVersion 32
  buildToolsVersion "32"

  defaultConfig {
    minSdkVersion 23
    targetSdkVersion 32

    // Version Information
    versionCode 1
    versionName "1.0.0"
    
    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
```

```
ns build android
Preparing project...
asset vendor.js 15.4 MiB [compared for emit] (name: vendor) (id hint: defaultVendor)
asset bundle.js 353 KiB [compared for emit] (name: bundle)
asset runtime.js 12.5 KiB [compared for emit] (name: runtime)
Entrypoint bundle 15.8 MiB = runtime.js 12.5 KiB vendor.js 15.4 MiB bundle.js 353 KiB
runtime modules 2.72 KiB 8 modules
orphan modules 576 bytes [orphan] 7 modules
modules by path ./node_modules/ 5.2 MiB
  javascript modules 4.94 MiB 560 modules
  json modules 273 KiB
    modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
    modules by path ./node_modules/css-tree/ 30.7 KiB 2 modules
modules by path ./src/ 125 KiB
  modules by path ./src/app/ 6.62 KiB 6 modules
  modules by path ./src/*.ts 840 bytes
    ./src/polyfills.ts 545 bytes [built] [code generated]
    ./src/main.ts 295 bytes [built] [code generated]
  ./src/app.css 118 KiB [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]
webpack 5.67.0 compiled successfully in 5591 ms
Webpack compilation complete.
Failed to build plugin @nativescript/core :
Error: spawn ./gradlew ENOENT
```

**Comment by CTOaramos** [comment]
Here's mine still getting the same error

app.gradle
`// You can add your native dependencies here
dependencies {
//  implementation 'androidx.multidex:multidex:2.0.1'
}

android {
  compileSdkVersion 32
  buildToolsVersion "32.0.0"
  // ndkVersion ""

  defaultConfig {
    minSdkVersion 17
    targetSdkVersion 32

    // Version Information
    versionCode 1
    versionName "1.0.0"
    
    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
`


`Preparing project...
asset vendor.js 6.07 MiB [compared for emit] (name: vendor) (id hint: defaultVendor)
asset bundle.js 342 KiB [compared for emit] (name: bundle)
asset runtime.js 11.5 KiB [compared for emit] (name: runtime)
Entrypoint bundle 6.42 MiB = runtime.js 11.5 KiB vendor.js 6.07 MiB bundle.js 342 KiB
runtime modules 2.46 KiB 7 modules
orphan modules 356 bytes [orphan] 6 modules
modules by path ./node_modules/@nativescript/core/ 1.37 MiB 185 modules
modules by path ./node_modules/css-tree/ 317 KiB 113 modules
modules by path ./app/ 123 KiB 8 modules
modules by path ./node_modules/source-map/lib/*.js 36.3 KiB 6 modules
modules by path ./node_modules/reduce-css-calc/dist/ 131 KiB 5 modules
modules by path ./node_modules/postcss-value-parser/lib/*.js 12.5 KiB
  ./node_modules/postcss-value-parser/lib/index.js 607 bytes [built] [code generated]
  + 4 modules
modules by path ./node_modules/mdn-data/css/*.json 242 KiB
  ./node_modules/mdn-data/css/at-rules.json 11.6 KiB [built] [code generated]
  + 2 modules
+ 4 modules
webpack 5.70.0 compiled successfully in 12722 ms
Webpack compilation complete.
(node:1935) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/aceramos/Desktop/ACE/DEV/MOBILE/Perennial/test-app/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to build plugin @nativescript/core : 
Error: spawn ./gradlew ENOENT`

**Comment by msl2000** [comment]
Having the same error as the first post of this thread, line by line. Is everyone in this thread having this issue using a Mac with an M1/M1 pro chip?

**Comment by rigor789** [comment]
Good news, I am able to reproduce the issue with node installed via Homebrew. I'm looking into it, but in the meantime, you can try installing node with a version manager like nvm, n, volta etc. That seems to work all around...

**Comment by rigor789** [comment]
I have pushed out a fix that should fix this - please try `nativescript@next` from npm: 

```bash
npm i -g nativescript@next
```

And then build again, and let me know if still running into an issue.

**Comment by CTOaramos** [comment]
Hi, @rigor789 MAN! YOU ARE A HERO!! Thank you; i was able to build now; 

`npm i -g nativescript@next` does it!;

**Comment by matteonatale** [comment]
Hi, @rigor789 I had the same issue since this morning (I'm working from Italy), then after a `npm i -g nativescript@next` plugins are built correctly and everything works fine. I'm curious to know where the problem was and how should we handle next versions of nativescript and gradle.

Thanks! 😆

**Comment by milosmatic** [comment]
@rigor789 I can confirm that the issue is gone. Excellent work!

**Comment by rigor789** [comment]
Thanks for confirming, will publish a patch release shortly...

As for why this was required, I frankly don't know - but node installed through Homebrew had trouble spawning a relative path command like `./gradlew` - it did spawn it - because the process ran and had logs outputting, but node would also throw the ENOENT error. This is not the case with the same node version installed through nvm for example, so it's quite puzzling. The fix I did was to always resolve `./<path>` spawns to a full path - which seems to work across all node installations.

**Comment by danielritter** [comment]
I have the same issue with v8.5.0 on a Rocky 9 linux virtual machine (build with TeamCity):

```
12:59:05   webpack 5.86.0 compiled with 3 warnings in 97999 ms
12:59:05   Webpack compilation complete. Watching for file changes.
12:59:13      ~ applying user-defined configuration from /srv/teamcity/agents/agent-2/work/85ceec441cda0047/mobile/apps/mobile-nativescript/App_Resources/Android/before-plugins.gradle
12:59:13   
12:59:13   FAILURE: Build failed with an exception.
12:59:13   
12:59:13   * Where:
12:59:13   Build file '/srv/teamcity/agents/agent-2/work/85ceec441cda0047/mobile/apps/mobile-nativescript/platforms/tempPlugin/core/build.gradle' line: 167
12:59:13   
12:59:13   * What went wrong:
12:59:13   A problem occurred evaluating root project 'core'.
12:59:13   > Invalid revision: build-tools_r33.0.2-linux.zip
12:59:13   
12:59:13   * Try:
12:59:13   > Run with --stacktrace option to get the stack trace.
12:59:13   > Run with --info or --debug option to get more log output.
12:59:13   > Run with --scan to get full insights.
12:59:13   
12:59:13   * Get more help at https://help.gradle.org
12:59:13   
12:59:13   BUILD FAILED in 5s
12:59:13   Failed to build plugin @nativescript/core :
12:59:13   Error: Command ./gradlew failed with exit code 1
12:59:13   Done.
12:59:13   
12:59:13   
12:59:13   
12:59:13    >  NX   Running target android for project mobile-nativescript failed
12:59:13   
12:59:13      Failed tasks:
12:59:13   
12:59:13      - mobile-nativescript:android
12:59:13   
12:59:13      Hint: run the command with --verbose for more details.
```

And my app.gradle looks like

```
// You can add your native dependencies here
dependencies {
//  implementation 'androidx.multidex:multidex:2.0.1'
}

android {
  compileSdkVersion 33
  buildToolsVersion "33.0.2"
  // ndkVersion ""

  defaultConfig {
    minSdkVersion 21
    targetSdkVersion 33

    // Version Information
    versionCode 1
    versionName "1.0.0"
    
    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}

```

On my local machine I can build successfully.

**Comment by rigor789** [comment]
@danielritter not sure where that revision string is coming from, but sound like that's the issue
>  Invalid revision: build-tools_r33.0.2-linux.zip

**Comment by danielritter** [comment]
@rigor789 Thanks, I had to delete the file build-tools_r33.0.2-linux.zip in the build-tools folder, I recently added it there before. Now it can build successfully. Thanks!
